### ISSUE TITLE
Implement Proper Validation for Username and Password in Login Page

### ISSUE THREAD

**Issue by elinabhasin** [mansiruhil13/Bobble-AI#10]
Hello @mansiruhil13 !

I noticed that the login.html  page currently does not validate the username and password inputs. Implementing proper validation is crucial for ensuring both security and a better user experience. Here are the specific improvements I propose:

**Username Validation:**

Check that the username is not empty.
Ensure the username meets certain criteria (e.g., length, allowed characters).

**Password Validation:**

Ensure the password field is not empty.
Implement checks for password strength, such as:
Minimum length (e.g., 8 characters)
Inclusion of uppercase letters, lowercase letters, numbers, and special characters.

**Feedback Messages:**

Provide user-friendly feedback messages for invalid inputs, guiding the user to correct them.

**Proposed Solution**: I would implement JavaScript validation functions that check these criteria before the form is submitted. This would enhance the overall security of the application and improve the user experience by preventing invalid submissions.

If this approach sounds good, I'd be happy to work on it and submit a pull request with the changes.

**Comment by mansiruhil13** [comment]
Ok.

**Comment by elinabhasin** [comment]
I just created a pull request with my changes—could you take a look and merge it if everything looks good?

**Comment by elinabhasin** [comment]
Hi! could you add a label to the issue?

**Comment by elinabhasin** [comment]
Thank you so much for the label but for getting my pull request to be counted in the leaderboard, i need a label of WOB or a similar one. Could you please do the same.
