### ISSUE TITLE
[Bug]: manage driver and manage ambulance in hospital dashboard, not clickable/ not working

### ISSUE THREAD

**Issue by mansiruhil13** [mansiruhil13/Bobble-AI#101]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

manage driver and manage ambulance in hospital dashboard, not working

### Add Screenshots

![Screenshot 2024-10-04 004556](https://github.com/user-attachments/assets/273f8029-d267-4dfb-86b5-60286c3502cd)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Shalinis19137** [comment]
Hello Sir, Can you please allot me this issue under Gssos-ext.

**Comment by SatyaD012** [comment]
@mansiruhil13 Hello,
I'd like to work on this issue. Please assign it to me.
