### ISSUE TITLE
[Bug]: Footer is Not Responsive on Different Screen Sizes

### ISSUE THREAD

**Issue by Ankul8471** [mansiruhil13/Bobble-AI#1011]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The current footer does not properly adjust to different screen sizes, leading to issues with layout and readability on mobile devices. This impacts the user experience, as important information in the footer may become cluttered or misaligned on smaller screens. I propose fixing the responsiveness of the footer to ensure it adapts seamlessly to various devices, maintaining a clean and organized appearance across all screen sizes. This enhancement will improve accessibility and overall site usability.

### Add Screenshots

![Screenshot 2024-10-22 002936](https://github.com/user-attachments/assets/31d57556-8fa8-4594-b539-3bbde51a7335)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by ritikraj2425** [comment]
@mansiruhil13 please assign this issue to me

**Comment by Ankul8471** [comment]
Please assign level 3 or at least level 2 for this issue
