### ISSUE TITLE
[Feature Request]: Logo

### ISSUE THREAD

**Issue by shreyad2806** [mansiruhil13/Bobble-AI#103]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I can add a personalized logo.
Please assign me under gssoc and hactoberfest.

### Use Case

Adding logo will help make your website more professional and asthetic.

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by shreyad2806** [comment]
![Screenshot 2024-10-04 213525](https://github.com/user-attachments/assets/ccf4c689-967d-4229-80f5-78923d2316df)

**Comment by mansiruhil13** [comment]
amazing, no need to write word ambuflow, only symbol is sufficient

**Comment by shreyad2806** [comment]
Okay then I am adding this and creating a pull request.
