### ISSUE TITLE
[Bug]: Social Media Links Open in Same Tab, Affecting User Experience

### ISSUE THREAD

**Issue by Ravi-1606** [mansiruhil13/Bobble-AI#1033]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When clicking on the social media links, they currently open in the same tab, which negatively impacts the user experience by navigating users away from the site. I attempted to manually open the links in a new tab but realized the current implementation does not specify the target="_blank" attribute. This attribute should be added to ensure that external links open in a new tab, allowing users to stay on the site while accessing social media profiles.

### Add Screenshots

https://github.com/user-attachments/assets/3be167b7-f286-49ea-b3e6-d69f469215e2

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Ravi-1606** [comment]
Please assign this task to me @mansiruhil13

**Comment by mansiruhil13** [comment]
footer issue assigned already, so make changes according to that.
