### ISSUE TITLE
[Feature Request]: Improve the UI of register & login page

### ISSUE THREAD

**Issue by sayanp607** [mansiruhil13/Bobble-AI#1034]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

the login and sign up option will be separated with proper stylings and authentication . But now, the page is totally messy. Please assign this task to me, I will fix the pages .

### Use Case

when user will come register , he will see sign up page and if he is already registered , then can navigate to login page, link will also be given there. and after that , he will redirect to home page  automatically.

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by arpit74170** [comment]
please assign this task to me , i have done with making 3 websites for client ,so i am best for it

**Comment by umeshmunde** [comment]
I can do this can you assign me for it. I also has a good knowledge of html, css ,js. or of other things
