### ISSUE TITLE
[Bug]: Login Page

### ISSUE THREAD

**Issue by Abhishek2634** [mansiruhil13/Bobble-AI#104]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

@mansiruhil13  Login page Ui is not good. i want to enhance its ui and make it responsive, assign this issue to me under gssoc, hacktoberfest label. thanks.
<img width="753" alt="Screenshot 2024-10-04 at 7 26 52 AM" src="https://github.com/user-attachments/assets/cacfabff-60a2-4080-8e54-69b17f0b3005">

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by devarsheecodess** [comment]
![image](https://github.com/user-attachments/assets/de1b6071-0e31-4d96-8209-8b1589be4d9e)
I had fixed the login page few days back, who did this now 🥹

**Comment by mansiruhil13** [comment]
but now buttons are overlapping.
