### ISSUE TITLE
[Feature Request]: Improving Social icons appearance 

### ISSUE THREAD

**Issue by PATILYASHH** [mansiruhil13/Bobble-AI#1148]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Social icons appearance are normal washout any hover effects and animations and interesting view
![image](https://github.com/user-attachments/assets/4ecbe9fd-c9d4-49d8-8f27-949c3e2a5c36)

### Use Case

by adding hover effects and animation it will become interesting

### Priority

Medium

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by mansa04** [comment]
can u assign me this issue
