### ISSUE TITLE
[Feature Request]: Addition of favicon icon / dark mode, scroll down option

### ISSUE THREAD

**Issue by TanushreeBorase** [mansiruhil13/Bobble-AI#115]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

adding scroll down so that user can come to bottom of page easily or top

### Use Case

This will improve ui and feasibility of website.

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by mansiruhil13** [comment]
but dark theme, already assigned

**Comment by mansiruhil13** [comment]
you can check previous issues of dark theme

**Comment by jyothimanoj12** [comment]
can you assign me this issue

**Comment by mansiruhil13** [comment]
> then should i add favicon or scroll up?

already there
