### ISSUE TITLE
[Bug]: Name Ambuflow wriiten in Hindi is wrong..

### ISSUE THREAD

**Issue by piyusdev2006** [mansiruhil13/Bobble-AI#1156]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

- When I visit the website and go through the content written in it.  I found the Hindi name of the website is written wrong. It feels weird to pronounce.

### Add Screenshots

- How it appears following a change.

![Screenshot 2024-11-02 072343](https://github.com/user-attachments/assets/3a575610-e658-4d6c-b757-8897ea553e6e)

- How it appears before change

![Screenshot 2024-11-02 072358](https://github.com/user-attachments/assets/831ba095-cade-4f8e-9c19-f524850e03be)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by mansiruhil13** [comment]
there are some blunders. name should be in English like before

**Comment by mansiruhil13** [comment]
there blunders created when translator button is added

**Comment by piyusdev2006** [comment]
ok i will do it.. inform you when completed before 8 nov

**Comment by piyusdev2006** [comment]
- Completed
