### ISSUE TITLE
[Feature Request]: Enhanced scroll back button with timeline on it for smoother functioning. 

### ISSUE THREAD

**Issue by shriyadindi** [mansiruhil13/Bobble-AI#1160]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Enhanced scroll back button with timeline on it for smoother functioning. 
![Screenshot 2024-10-31 115055](https://github.com/user-attachments/assets/7afe9ac1-50ea-4bd4-ace6-54c8ee511acd)

### Use Case

Scroll back button css styling.

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by nihalaniharsh** [comment]
Could you please assign the issue to me ? I' am eager to drive in and make a meaningful impact .Thankyou for considering my request!"
