### ISSUE TITLE
[Feature Request]: Addition of nav bar to the website 

### ISSUE THREAD

**Issue by gjrahul1** [mansiruhil13/Bobble-AI#1168]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I wanted to add a nav bar to this project and make it user friendly. Assign me the project @mansiruhil13 Add gssoc-ext , hactoberfest - accepted and level to this issue.

Current Status: div class
Need for improvement: nav bar

![Screenshot 2024-11-05 024214](https://github.com/user-attachments/assets/322ddedd-27b8-442d-aaec-431567f6fefe)

### Use Case

It would make the debugging easier 

### Benefits

Easy navigation and enhancing proper website structure

### Priority

Medium

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by mansiruhil13** [comment]
navbar there. 
![Screenshot 2024-11-05 120639](https://github.com/user-attachments/assets/a461e799-6872-44f5-80b2-dafaa909136c)

**Comment by KanishkRajTech** [comment]
Hi! Could you please assign this bug to me? I’d like to work on fixing it.
