### ISSUE TITLE
[Bug]: Inconsistent footers

### ISSUE THREAD

**Issue by Anushkam09** [mansiruhil13/Bobble-AI#1178]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The footers are not consistent. 
Page 1:
![image](https://github.com/user-attachments/assets/19f517c3-ada1-4ad2-82bb-0d3aab037171)

Other pages:
![image](https://github.com/user-attachments/assets/705f4b0f-2a4e-4a8d-b48b-4c56a392041c)

I would like to make it consistent over all pages

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by nihalaniharsh** [comment]
Could you please assign the issue to me ? I' am eager to drive in and make a meaningful impact .Thankyou for considering my request!"

**Comment by mansiruhil13** [comment]
2nd one is correct. due to some blunders, footers have been changed on homepage
