### ISSUE TITLE
[Feature Request]: Ading a contributors page

### ISSUE THREAD

**Issue by Son7c** [mansiruhil13/Bobble-AI#1185]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would make a new webpage dedicated to the contributors of this project which displays the stats of contribution on this project by the contributors, i would also add cool animation when contributors cards are hovered.

### Use Case

This would show the stats of this project

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Son7c** [comment]
@mansiruhil13 Please assign me this issue

**Comment by hardikguptaofficialgit** [comment]
Kindly Assign me this task
