### ISSUE TITLE
[Bug]: To add links in all the components of footer 

### ISSUE THREAD

**Issue by ishakatiyar06** [mansiruhil13/Bobble-AI#1186]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/user-attachments/assets/8673700e-50c1-4a39-8a93-462b15a16c98)
Adding links in this section

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by hardikguptaofficialgit** [comment]
Kindly Assign me this task
