### ISSUE TITLE
[ MISSING ] : anchor tags in USEFUL links section in FOOTER 

### ISSUE THREAD

**Issue by shreyaspathki** [mansiruhil13/Bobble-AI#1188]
### Issue: Missing Anchor Tags in Footer Links

**Description:**  
The "Useful Links" section in the footer currently uses `<p>` tags instead of `<a>` tags, causing the links to be non-clickable. Update the footer code to use `<a>` tags for each link under "Useful Links" to make them functional.

**Expected Behavior:**  
Links should use `<a>` tags to enable click functionality and navigate to the relevant pages.

**Suggested Fix:**  
Replace `<p>` tags with `<a>` tags in the footer's "Useful Links" section.

![Screenshot 2024-11-06 204937](https://github.com/user-attachments/assets/02a3ba53-ba1f-456b-84f4-0e013556e7b3)

**Comment by shreyaspathki** [comment]
@mansiruhil13 please assign me this task under gssoc24 extd and hacktoberfest 2024

**Comment by SparshKhanna0001** [comment]
@mansiruhil13 kindly add the gssoc extd tag

**Comment by KanishkRajTech** [comment]
Hi! Could you please assign this bug to me? I’d like to work on fixing it.
