### ISSUE TITLE
[Bug]: Adjusting mail logo and its palceholder

### ISSUE THREAD

**Issue by ishakatiyar06** [mansiruhil13/Bobble-AI#1196]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In the contact us section, the logo of mai and text is overlapping.

### Add Screenshots

<img width="270" alt="image" src="https://github.com/user-attachments/assets/55428213-4263-420b-a67a-3ee80cff4f15">

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by dishaagarwal04** [comment]
I want to on work  that issue is still not the right place
