### ISSUE TITLE
[Feature Request]:  Add Signup/Register page 

### ISSUE THREAD

**Issue by Subhajit-2023-44** [mansiruhil13/Bobble-AI#1223]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to create a  Signup/Register page and a Signup/Register page button in the home page navbar that redirects to the Signup/Register page...

![image](https://github.com/user-attachments/assets/90fcc34a-1549-4c53-aa6f-b0004f6a6dae)

### Use Case

.

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by mansiruhil13** [comment]
page already there.
