### ISSUE TITLE
login page can be better

### ISSUE THREAD

**Issue by sakshamsaraf23** [mansiruhil13/Bobble-AI#126]
@mansiruhil13 
instead of using solid colors in the background of the login page u can add background images to make it look more visually applealing so if u want to u can assign me the issue

**Comment by mansiruhil13** [comment]
![Screenshot 2024-10-04 225555](https://github.com/user-attachments/assets/98dfaf36-50e2-4927-b896-f48dca2a8be4)
there are many changes in login page
before:
![373623876-de1b6071-0e31-4d96-8209-8b1589be4d9e](https://github.com/user-attachments/assets/199927cb-52f7-4f76-b201-969f1f4a9fb2)

**Comment by mansiruhil13** [comment]
login page is resolved
![Screenshot 2024-10-04 231428](https://github.com/user-attachments/assets/64737ddc-38c8-47fc-a7bd-979f19202c4a)

**Comment by sakshamsaraf23** [comment]
mam i think instead of this white background if there is a background image in the login page that will make it look more visually apealing

**Comment by Abbas7120** [comment]
Mam login page is resolved with only UI section so for login page functionality of accepting username password after registration please assign it to him so that he can correct it or I am present for its correction and also say him to remove header section of this so it would be more  better

**Comment by Abbas7120** [comment]
Ok ! I will do the change

**Comment by sakshamsaraf23** [comment]
@mansiruhil13 mam i agree with his i have many images but the current ui of the sign up page looks better then that so i have applied the same colors to the sogn up page and also when we click the sign up in the login page it didn't showed any response so i have fixed that too.

**Comment by sakshamsaraf23** [comment]
mam do add the label of level so that the contribution can count

**Comment by mansiruhil13** [comment]
changes doesn't happen

**Comment by sakshamsaraf23** [comment]
mam do check again for the changes and please remove the python tag from the project description on the Gssoc webstite because we are not using python in anything here

**Comment by mansiruhil13** [comment]
> mam do check again for the changes and please remove the python tag from the project description on the Gssoc webstite because we are not using python in anything here

how can i remove?

**Comment by mansiruhil13** [comment]
> mam do check again for the changes and please remove the python tag from the project description on the Gssoc webstite because we are not using python in anything here

![Screenshot 2024-10-05 174644](https://github.com/user-attachments/assets/bd4f185c-9660-49a4-825f-cc6d41910242)

**Comment by sakshamsaraf23** [comment]
i m sorry i don't know what is the problem i downloaded the file again and ran it in my local system and the output it showed is:
![Screenshot 2024-10-05 174921](https://github.com/user-attachments/assets/41d7627b-fb5e-4fd8-943d-bdfb6b815f21)

**Comment by sakshamsaraf23** [comment]
> > mam do check again for the changes and please remove the python tag from the project description on the Gssoc webstite because we are not using python in anything here
> 
> how can i remove?

i m sorry i don't know how to

**Comment by sakshamsaraf23** [comment]
@mansiruhil13 mam i m updated it again and i m sending the PR again please check it
