### ISSUE TITLE
[Feature Request]: The header of the Ambulance Tracking System website could be made stickey

### ISSUE THREAD

**Issue by shubhamjh15** [mansiruhil13/Bobble-AI#131]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

i can make the header stickey
![Screenshot 2024-10-04 232346](https://github.com/user-attachments/assets/b887c945-bd61-4627-9755-8616b771438b)
![Screenshot 2024-10-04 232324](https://github.com/user-attachments/assets/5b67d6b2-e8f8-4ede-a5fa-bce6e309d13e)

### Use Case

A stickey header will make navigation easy, improved user experience for long pages .

### Benefits

Enhanced usability and navigation, improved user experience , better branding and consistency

### Priority

High

### Record

- [x] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by mansiruhil13** [comment]
like example? with better ui
