### ISSUE TITLE
Home page could be better

### ISSUE THREAD

**Issue by Sanskriti65** [mansiruhil13/Bobble-AI#132]
Home page could be better.
  and there were 2 home page 
1. with the name of bobble ai which is totaly blank.
![image](https://github.com/user-attachments/assets/0626189d-9f92-4377-ade7-36c4dbf7da0c)

2. the ambulance tracking we can change the look  of Faq section by reducing its size which is much bigger in size that is not needed
![image](https://github.com/user-attachments/assets/fddf3fbe-72f6-4e1b-a614-4aefbbda466d)

**Comment by mansiruhil13** [comment]
also you can change logo for eg:
![373716444-ccf4c689-967d-4229-80f5-78923d2316df](https://github.com/user-attachments/assets/015a2f3d-55a9-4c96-bf43-0e8da6a1b5e1)
*that bobble ai is just random name of repo
*no need of the word ambuflow in logo
and 
also i have checked now, header buttons home, features.. are not working/clickable

**Comment by Sanskriti65** [comment]
I'll  change the logo also  and i dont think we need 2 home page we can use only one which is showing the logo or should we add that part in the 1st home page

**Comment by Abbas7120** [comment]
Sanskriti aapne sahi decision liya hai iska homepage aap behtar banao I suggest you to add Footer in home page as well as add an image in home page like Uber Website and in second home page remove login / get started section as when user Login he directly reach to that page after login and not require any login in that .

**Comment by Abbas7120** [comment]
I also suggest you to add all header section in this page i.e.  home feature team contact Sanskriti

**Comment by Sanskriti65** [comment]
> I also suggest you to add all header section in this page i.e. home feature team contact Sanskriti
oky abbas lets do it

**Comment by Abbas7120** [comment]
Sanskriti which page you are choosing to do change

**Comment by Sanskriti65** [comment]
it will take time but i think we have lots of ideas we can do it and make this one more good

**Comment by Sanskriti65** [comment]
im changing the logos of all the page  so that we have a logo which represent this website

**Comment by Abbas7120** [comment]
Yeah its true but I see that ki 2nd home page is better so it require less changes instead of this 1st page require a major improvement

**Comment by Sanskriti65** [comment]
yeah it take time firstly we have to decide what user get when they login

**Comment by Abbas7120** [comment]
so after login he  should get 2nd page

**Comment by Sanskriti65** [comment]
ik he'll get 2nd page where they get all the benefit of website which is our 2nd home page

**Comment by Abbas7120** [comment]
So I recommend you to do second page adjustment i.e. remove login section and add logout with functionality of logout and add correct logo and I do first page correction

**Comment by Abbas7120** [comment]
Its my decision aap apna batado!

**Comment by Sanskriti65** [comment]
gud idea

**Comment by Sanskriti65** [comment]
what you guys think about this logo @mansiruhil13 
![logo12-removebg-preview](https://github.com/user-attachments/assets/4c4aa925-9292-43d9-b4a5-f7caaf15a63c)

**Comment by Abbas7120** [comment]
its good but focussed on code side rather than logo just commit code with this logo ...

**Comment by Sanskriti65** [comment]
yeah im just want suggestion because im  if im changing the logo then you we have to work accordingly otherwise it will look odd

**Comment by Abbas7120** [comment]
Ok ! that ' s a nice descision

**Comment by mansiruhil13** [comment]
> So I recommend you to do second page adjustment i.e. remove login section and add logout with functionality of logout and add correct logo and I do first page correction

but login and logout section is must

**Comment by mansiruhil13** [comment]
> what you guys think about this logo @mansiruhil13 ![logo12-removebg-preview](https://private-user-images.githubusercontent.com/138789759/373780102-4c4aa925-9292-43d9-b4a5-f7caaf15a63c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgwNzExNDUsIm5iZiI6MTcyODA3MDg0NSwicGF0aCI6Ii8xMzg3ODk3NTkvMzczNzgwMTAyLTRjNGFhOTI1LTkyOTItNDNkOS1iNGE1LWY3Y2FhZjE1YTYzYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNFQxOTQwNDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMmRkYzQ2N2IyOGNlM2FjMGVkNTkzYmM3N2ZhMzM5YWU3N2M0N2EyNjM4MGM1NGM5NjM4M2MxNzYyZTFmZmY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.BWacFNesYRxCnKgdgcZA9EJ3qseJ5KdbNzf3Uma8KPI)

amazing

**Comment by mansiruhil13** [comment]
> currently I'm working on this home page ![image](https://private-user-images.githubusercontent.com/138789759/373781914-d34e64b1-dedc-4756-8628-b0bf93afa239.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgwNzExMTcsIm5iZiI6MTcyODA3MDgxNywicGF0aCI6Ii8xMzg3ODk3NTkvMzczNzgxOTE0LWQzNGU2NGIxLWRlZGMtNDc1Ni04NjI4LWIwYmY5M2FmYTIzOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNFQxOTQwMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOTQ4YTFhNzAyYjRkODA1ZDQyY2VlY2FhNzZmZWRkN2U3YzIyYmJlMTc0MmUzYjYzZDQwYTg0Nzk2N2MwYTQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.VDcteEAoj07BPS6K7iO2x1_3-ZCaOx2OXQBAKUKRz7M)

no need for change in frequently asked ques

**Comment by Sanskriti65** [comment]
> > currently I'm working on this home page ![image](https://private-user-images.githubusercontent.com/138789759/373781914-d34e64b1-dedc-4756-8628-b0bf93afa239.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgwNzExMTcsIm5iZiI6MTcyODA3MDgxNywicGF0aCI6Ii8xMzg3ODk3NTkvMzczNzgxOTE0LWQzNGU2NGIxLWRlZGMtNDc1Ni04NjI4LWIwYmY5M2FmYTIzOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNFQxOTQwMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOTQ4YTFhNzAyYjRkODA1ZDQyY2VlY2FhNzZmZWRkN2U3YzIyYmJlMTc0MmUzYjYzZDQwYTg0Nzk2N2MwYTQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.VDcteEAoj07BPS6K7iO2x1_3-ZCaOx2OXQBAKUKRz7M)
> 
> no need for change in frequently asked ques

I'm just changing the look of this section.

**Comment by Sanskriti65** [comment]
> > what you guys think about this logo @mansiruhil13 ![logo12-removebg-preview](https://private-user-images.githubusercontent.com/138789759/373780102-4c4aa925-9292-43d9-b4a5-f7caaf15a63c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgwNzExNDUsIm5iZiI6MTcyODA3MDg0NSwicGF0aCI6Ii8xMzg3ODk3NTkvMzczNzgwMTAyLTRjNGFhOTI1LTkyOTItNDNkOS1iNGE1LWY3Y2FhZjE1YTYzYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNFQxOTQwNDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMmRkYzQ2N2IyOGNlM2FjMGVkNTkzYmM3N2ZhMzM5YWU3N2M0N2EyNjM4MGM1NGM5NjM4M2MxNzYyZTFmZmY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.BWacFNesYRxCnKgdgcZA9EJ3qseJ5KdbNzf3Uma8KPI)
> 
> amazing

Oky so the logo is confirmed 👍

**Comment by Sanskriti65** [comment]
> > So I recommend you to do second page adjustment i.e. remove login section and add logout with functionality of logout and add correct logo and I do first page correction
> 
> but login and logout section is must

We need login only on 1st page when user login then the 2nd page will display where their is no need of login only logout button will display
