### ISSUE TITLE
[Bug]: FAQs section can be made better

### ISSUE THREAD

**Issue by Deepanshu-pathak** [mansiruhil13/Bobble-AI#133]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

FAQ section is very dull and also taking very much space , i can organise faq section neatly , providing styling and smooth transition

### Add Screenshots

![Screenshot 2024-10-04 233540](https://github.com/user-attachments/assets/e44a6460-9d2d-40a1-b5eb-ae19ae88bcf0)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by mansiruhil13** [comment]
like how? can you give the outlook design, how you made look better

**Comment by Deepanshu-pathak** [comment]
@mansiruhil13 firstly neumorphic effect is not so visually appealing and also transition when clicked is not so smooth and questions are arranged one by one vertically which requires scolling , ican make it in grid format so scrolling is not required and also add some text color matching with theme because black n white is not the right call. 
i hope u understand now and thanku for assigning me this issue
