### ISSUE TITLE
[Feature Request]: dark mode 

### ISSUE THREAD

**Issue by Chandravan** [mansiruhil13/Bobble-AI#141]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Implement a dark mode option to enhance user experience by reducing eye strain, improving readability in low-light environments, and offering a sleek, modern aesthetic.

### Use Case

To provide users with the ability to toggle between light and dark modes for a more comfortable viewing experience, especially in low-light environments.

### Benefits

Reduces eye fatigue during prolonged usage.
Enhances user comfort in low-light conditions.
Provides a visually appealing alternative for users who prefer a darker aesthetic.

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Chandravan** [comment]
please assign this issue/task to me. I'd love to work on it.

**Comment by mansiruhil13** [comment]
> please assign this issue/task to me. I'd love to work on it.

dark theme already assigned
