### ISSUE TITLE
"Revamping the Navbar: Contributing to an Open-Source Project for a Sleek and Modern Design"

### ISSUE THREAD

**Issue by khurshed07** [mansiruhil13/Bobble-AI#161]
********************************Before Changes****************************
![Screenshot 2024-10-05 161550](https://github.com/user-attachments/assets/6af4c566-2466-4e33-8f83-054d3f0fc608)

*******************************After Chnages*****************************
![Screenshot 2024-10-05 161204](https://github.com/user-attachments/assets/4afa605f-50e2-403f-9c2b-d65161760e0b)
![Screenshot 2024-10-05 161211](https://github.com/user-attachments/assets/db31c47e-c8f6-45e9-9285-1d95637cd8a7)
![Screenshot 2024-10-05 161219](https://github.com/user-attachments/assets/83499142-a518-403b-af0b-b4a822936254)
![Screenshot 2024-10-05 161227](https://github.com/user-attachments/assets/65a32e45-d0b8-4d28-a39f-b1ce80feb188)
![Screenshot 2024-10-05 161239](https://github.com/user-attachments/assets/9716dff7-57a3-4cba-bda2-35b8538c0203)

Hi @mansiruhil13

I recently updated the navbar and font-family for your project to make it more attractive and user-friendly. I've attached screenshots of the changes, and I'd love to contribute this enhancement to improve the overall design.

Could you kindly assign me to this task? It would be a great opportunity for me to contribute while enhancing my skills.

Looking forward to your response!

Best regards,
@khurshed07
https://github.com/khurshed07

**Comment by mansiruhil13** [comment]
can you change the design?

**Comment by mansiruhil13** [comment]
its' the landing page, and home features.. are on the header section

**Comment by mansiruhil13** [comment]
use logo like ambulance, not bobble ai. bobble ai is just random name of repos. you can check prev issues for logo. there is change in logo

**Comment by khurshed07** [comment]
Okay

**Comment by khurshed07** [comment]
Hi @mansiruhil13 
please correct GSSOC'24 extd label so that its count as a point in gssoc'24 extd
Thank you
