### ISSUE TITLE
[Feature Request]: i would like to improve the footer section

### ISSUE THREAD

**Issue by jyothimanoj12** [mansiruhil13/Bobble-AI#163]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

i want to imrove the footer section of the page from this

![Screenshot 2024-10-05 170532](https://github.com/user-attachments/assets/eeb63dc3-28bb-4880-b102-07ddd0fc0729)

to something like this

![Screenshot 2024-10-05 153143](https://github.com/user-attachments/assets/8727edf2-468f-4093-a879-134f09f0bffa)

please allow me to work on this issue under gsoc ext

### Use Case

Enhanced User Experience
Improved Site Navigation

### Priority

Medium

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by jyothimanoj12** [comment]
plz assign me this issue under gsoc extended

**Comment by jyothimanoj12** [comment]
done 👍

**Comment by jyothimanoj12** [comment]
#164  plz assign points to me for it

**Comment by jyothimanoj12** [comment]
@mansiruhil13 it seems like i was not awarded points for this contribution

**Comment by mansiruhil13** [comment]
> @mansiruhil13 it seems like i was not awarded points for this contribution

yes may ne due to labels. but now labels correction sorted out. and the faq page assigned now for better ui improvement

**Comment by jyothimanoj12** [comment]
Ok

**Comment by jyothimanoj12** [comment]
> > @mansiruhil13 it seems like i was not awarded points for this contribution
> 
> 
> 
> yes may ne due to labels. but now labels correction sorted out. and the faq page assigned now for better ui improvement

What labels ??

**Comment by mansiruhil13** [comment]
> > > @mansiruhil13 it seems like i was not awarded points for this contribution
> > 
> > 
> > yes may ne due to labels. but now labels correction sorted out. and the faq page assigned now for better ui improvement
> 
> What labels ??

label1,2,3 and gssoc-ext

**Comment by jyothimanoj12** [comment]
ok
