### ISSUE TITLE
to give better UI to footer

### ISSUE THREAD

**Issue by Ishika-Gupta06** [mansiruhil13/Bobble-AI#168]
![Screenshot 2024-10-05 185713](https://github.com/user-attachments/assets/c8fdac7e-e116-4768-ad65-c5074788a53a)
@mansiruhil13 please assign me this task under GSsoc-ext, hacktoberfest and level-1,2,3

**Comment by mansiruhil13** [comment]
also links of social media are not working and for contact: you can use, mail=emergency@ambulanceservice.in , phone = +91-911-1234567 , location = 123 Emergency Lane, Mumbai, India ( for reference  )

**Comment by harish08102004** [comment]
Hey @mansiruhil13 if nobody is working on this issue I can work on it.
