### ISSUE TITLE
Restructure Repo Directory

### ISSUE THREAD

**Issue by yashksaini-coder** [mansiruhil13/Bobble-AI#17]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The current repository directory structure needs reorganization to enhance clarity and accessibility. This task involves refactoring the directory layout to better align with project conventions, separating concerns (e.g., code, documentation, assets), and ensuring easier navigation for contributors. Update the README file and any configuration files to reflect the new structure.

### Use Case

The current repository structure is cluttered, making it difficult for contributors to locate files, or understand the workflow, and maintain consistency. I will create a clear separation between HTML files, images, and assets, improving navigation for new developers. 

### Benefits

- Good repo structure
- Easy navigation
- Better approach for new developers

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by yashksaini-coder** [comment]
Hi @mansiruhil13 I would like to work on this issue. I have raised this after discussing it with @sanaa9012
Assign this issue to both of us.

**Comment by mansiruhil13** [comment]
> Hi @mansiruhil13 I would like to work on this issue. I have raised this after discussing it with @sanaa9012 Assign this issue to both of us
> 
> @yashksaini-coder & @sanaa9012

issue is to enhance live location of ambulance on google map

**Comment by yashksaini-coder** [comment]
> > Hi @mansiruhil13 I would like to work on this issue. I have raised this after discussing it with @sanaa9012 Assign this issue to both of us
> > @yashksaini-coder & @sanaa9012
> 
> issue is to enhance live location of ambulance on google map

okh. Also can you add labels and close this issue as resolved

**Comment by yashksaini-coder** [comment]
@mansiruhil13 add level labels to this issue

**Comment by yashksaini-coder** [comment]
@mansiruhil13 can you assign me on this issue
