### ISSUE TITLE
[Bug]: signup page not working in login page

### ISSUE THREAD

**Issue by Anandha-Vihari** [mansiruhil13/Bobble-AI#175]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

in login page ,sign up option is not working
so,
i added signup page and refered its link in login page
i created a pull request
try to give level 3 
thanks

### Add Screenshots

https://github.com/user-attachments/assets/2f545b52-7dbb-49ee-91f0-3d7446f17d26

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by mansiruhil13** [comment]
yes
