### ISSUE TITLE
Add Hospital Background Image to Website

### ISSUE THREAD

**Issue by aparna-44** [mansiruhil13/Bobble-AI#176]
there a could be a landing page background image  for  making the website more relevant to its healthcare purpose,else we can also add image which resembles website.
@mansiruhil13 
can you plz assign me this issue,i really i wanted to work on it.

**Comment by mansiruhil13** [comment]
before pr, can you share the final output?

**Comment by uzefaqureshi06** [comment]
Hi , I hope you're doing well. I I believe I can contribute effectively, and I'm eager to help resolve it. If it's possible, could you please assign me this task? I would really appreciate the opportunity. Thank you!"

**Comment by uzefaqureshi06** [comment]
@aparna-44 hey I have raised the PR can you please review it and merge it
