### ISSUE TITLE
[Feature Request]: adding favicon icon

### ISSUE THREAD

**Issue by solanki505** [mansiruhil13/Bobble-AI#185]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

![Screenshot 2024-10-05 212839](https://github.com/user-attachments/assets/d97e8ef4-0788-428e-9804-57fbe1a59d98)

### Use Case

it will male the site more user friendly

### Priority

Medium

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by mansiruhil13** [comment]
fav icon removed by glitch
