### ISSUE TITLE
[Feature Request]: adding move to top icon in page

### ISSUE THREAD

**Issue by solanki505** [mansiruhil13/Bobble-AI#186]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

it will help to move to the top directly

### Use Case

makes it more user friendly

### Priority

Medium

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by mansiruhil13** [comment]
assigned already
