### ISSUE TITLE
[Feature Request]: Add favicon to your website

### ISSUE THREAD

**Issue by SurajSG23** [mansiruhil13/Bobble-AI#188]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hey, i noticed that your website don't have any favicon , i would like to design a favicon and add it !

![image](https://github.com/user-attachments/assets/4d3b6328-99fd-4bfa-83a6-eab4b3cba7e0)

Please assign me this under gssoc and hacktober fest .THANK YOU

### Use Case

Favicon is and important feature every website should have, favicon gives a unique identity for your website.

### Priority

Medium

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by mansiruhil13** [comment]
assigned already
