### ISSUE TITLE
Enhance Live Location on Google Maps for Driver and Ambulance

### ISSUE THREAD

**Issue by yashksaini-coder** [mansiruhil13/Bobble-AI#19]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to enhance the live location tracking on Google Maps to display the real-time location of drivers and ambulances. This feature should update live location data on the map for users, including the ambulance and driver’s positions. It would function similarly to real-time tracking on Google Maps, providing continuous location updates.

### Use Case

This feature will allow users and hospital staff to track the exact position of ambulances and drivers in real-time. It can improve response times during emergencies and ensure better coordination between patients, drivers, and hospitals.

### Benefits

- Increased efficiency in managing and tracking emergency vehicles.
- Better coordination for patient pickups and hospital visits.
- Real-time updates provide users with transparency and reliability.

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by yashksaini-coder** [comment]
@mansiruhil13 can you assign the issue and add labels to this issue.

**Comment by mansiruhil13** [comment]
> @mansiruhil13 can you assign the issue and add labels to this issue.

https://github.com/mansiruhil13/Bobble-AI/issues/1#issuecomment-2380723339
