### ISSUE TITLE
[Bug]: homepage fix

### ISSUE THREAD

**Issue by mansiruhil13** [mansiruhil13/Bobble-AI#199]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Add Screenshots

![Screenshot 2024-10-05 222503](https://github.com/user-attachments/assets/f3d4c874-1147-4630-a906-34c7fe31020d)

**Comment by mansiruhil13** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### What happened?
> there is a change in whole setup of homepage
> 
> ### Add Screenshots
> ![Screenshot 2024-10-05 222503](https://private-user-images.githubusercontent.com/157950124/373888567-f3d4c874-1147-4630-a906-34c7fe31020d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxNDc3MDksIm5iZiI6MTcyODE0NzQwOSwicGF0aCI6Ii8xNTc5NTAxMjQvMzczODg4NTY3LWYzZDRjODc0LTExNDctNDYzMC1hOTA2LTM0YzdmZTMxMDIwZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNVQxNjU2NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYzg5YWU0MDVhZDI1ZGNkYTNlOTBhMDcxNjI2NmVkNmQ4ZGU5OTQ1OWFkNDBkNDFhNTEzY2VjNTBlMDRkNDgzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.mT7jTTTNpvaCJpH-cW_x_YQgqrIqYc8NN2Y2ShSU0F4)
>

**Comment by poorvikaa08** [comment]
![image](https://github.com/user-attachments/assets/debb42b5-ab06-4e59-9756-099d9948fdf9)

@mansiruhil13 This issue exists

**Comment by poorvikaa08** [comment]
I will fix this issue
@mansiruhil13 Would you assign it to me

**Comment by Anandha-Vihari** [comment]
already fixed

**Comment by poorvikaa08** [comment]
It's not yet resolved

**Comment by Anandha-Vihari** [comment]
@poorvikaa08 i already fixed it ,it is wating in PR's,once the maintainer approves it will be live

**Comment by poorvikaa08** [comment]
Nobody was assigned, right?
Can you create a pull request without getting assigned for the issue??

@Anandha-Vihari How does it work?

**Comment by poorvikaa08** [comment]
Dude, I thought we must get assigned first, make or fix any changes, and then make PRs.
I didn't know we could work on the issues
