### ISSUE TITLE
display confirmation message after submitting newsletter form

### ISSUE THREAD

**Issue by ananyag309** [mansiruhil13/Bobble-AI#203]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

to display confirmation message after submitting newsletter form

### Use Case

its important user gets a positive response that there response has been recorded 

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Akanshaku** [comment]
I would like to work on this issue pls assign me this @mansiruhil13
