### ISSUE TITLE
[Bug]: landing page issue

### ISSUE THREAD

**Issue by 4F24L** [mansiruhil13/Bobble-AI#208]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Landing page messes up 

https://github.com/user-attachments/assets/f02146c7-e303-4bd7-b20b-31338c2d056c

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by devarsheecodess** [comment]
#199
