### ISSUE TITLE
[Bug]: footer section bug

### ISSUE THREAD

**Issue by mansiruhil13** [mansiruhil13/Bobble-AI#211]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Add Screenshots

![Screenshot 2024-10-06 010719](https://github.com/user-attachments/assets/6c1d18e7-818f-44c8-a055-1466815acfe8)

**Comment by 4F24L** [comment]
@mansiruhil13 would you want to work on this ??

**Comment by mansiruhil13** [comment]
> @mansiruhil13 would you want to work on this ?? If not, I can fix then !!

i am unable to do, that's why i create an issue

**Comment by mansiruhil13** [comment]
> @mansiruhil13 would you want to work on this ?? If not, I can fix then !!

i am unable to do

**Comment by 4F24L** [comment]
assign me then !!

**Comment by mansiruhil13** [comment]
> @mansiruhil13 assign me then !! and please add level 2

i am working on it

**Comment by 4F24L** [comment]
> > @mansiruhil13 assign me then !! and please add level 2
> 
> i am working on it

Okay !!

**Comment by mansiruhil13** [comment]
> > > @mansiruhil13 assign me then !! and please add level 2
> > 
> > 
> > i am working on it
> 
> Okay !!

![Screenshot 2024-10-06 015709](https://github.com/user-attachments/assets/52c07a99-56e6-46b4-befc-6af83a05657f)
i tried, some changes done. but can you improve the ui part?

**Comment by 4F24L** [comment]
I solved all bugs and fixed them. will you please add level 3..  for this 3AM work? 😉

**Comment by 4F24L** [comment]
The last commit isn't deployed correctly. Committing again can cause conflicts.

Close this issue, I am creating a new issue. where conflicts will not occur.
