### ISSUE TITLE
Fix Direct Link to Home Section 🔗

### ISSUE THREAD

**Issue by LitZeus** [mansiruhil13/Bobble-AI#218]
The link to the `Home` section is currently not functioning correctly. 
This issue needs to be addressed to ensure that users can easily navigate back to the Home page.  🏠

### Please add hactoberfest and GSSoC24 tag. You can assign me for this issue.

**Comment by 4F24L** [comment]
Can you add Screenshot or video clip ? 

Always add some screenshot or video clip of whenever you are raising an issue.
