### ISSUE TITLE
Add Logo to Title Bar 🖼️

### ISSUE THREAD

**Issue by LitZeus** [mansiruhil13/Bobble-AI#219]
# The title bar currently lacks branding due to the absence of a logo. 
### Please add hactoberfest and GSSoC24 tag. You can assign me for this issue.

**Comment by 4F24L** [comment]
Always add some screenshots or video clips that support your issue, or we can check them without going to the website.

**Comment by LitZeus** [comment]
## @mansiruhil13 you can see the issue in the following screenshot:
![Screenshot 2024-10-06 171738](https://github.com/user-attachments/assets/1b2b962e-33cd-4f71-afc8-8055193070de)
