### ISSUE TITLE
[Feature Request]: GoogleAuthorization using Firebase

### ISSUE THREAD

**Issue by samriddhitiwary** [mansiruhil13/Bobble-AI#235]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to request the addition of Google Authorization using Firebase in our project. This feature would allow users to authenticate using their Google accounts, streamlining the sign-in process and enhancing user experience. Firebase provides a robust authentication solution that can simplify the integration of Google Sign-In, making it easier for users to access the application without having to create a new account or remember another password.

### Use Case

Implementing Google Authorization would greatly enhance user interaction with our application. For example, a user could easily sign in with their Google account when accessing our service, allowing them to save their preferences and data without the hassle of traditional registration processes. This would not only speed up onboarding for new users but also improve security, as Firebase handles user data securely.

### Benefits

Improved User Experience: Users can sign in quickly and easily with their Google accounts, reducing barriers to entry.
Enhanced Security: Firebase Authentication provides built-in security features, minimizing vulnerabilities associated with password management.
Increased User Retention: Simplifying the sign-in process can lead to higher user satisfaction and retention rates.
Scalability: Firebase handles user authentication seamlessly, allowing our application to scale without worrying about user management.

![image](https://github.com/user-attachments/assets/b8b62f35-278e-46bc-a197-eb49965b27f1)

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by samriddhitiwary** [comment]
@mansiruhil13 Could you please assign this issue to me under GSSoC-exd level3 and Hacktoberfest label

**Comment by mansiruhil13** [comment]
but login page has been changed
**screenshot**
![Screenshot 2024-10-06 200234](https://github.com/user-attachments/assets/89f0545f-5c16-4b3a-b302-dd3fa3b4c189)
![Screenshot 2024-10-06 200246](https://github.com/user-attachments/assets/885fdeff-3b51-44d2-bd25-59d41f3831df)
