### ISSUE TITLE
[Feature Request]: Forget password feature

### ISSUE THREAD

**Issue by meghanakn473** [mansiruhil13/Bobble-AI#243]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The **"Forgot Password"** feature in the Bobble AI project enables users to securely reset their passwords in case they forget them. Accessible via a link on the login page, this feature allows users to enter their registered email or phone number to receive a secure password reset link. Once verified, users are directed to a dedicated page where they can set a new password. To enhance security, the feature includes measures such as limiting the number of reset requests and implementing CAPTCHA verification to prevent unauthorized access. By providing a reliable way to regain account access, this feature significantly improves user experience and fosters trust in the application.

### Use Case

Users may forget their passwords and require a secure and user-friendly way to reset them. Currently, there is no "Forgot Password" feature implemented, users might face difficulties accessing their accounts, leading to frustration and a poor user experience.

### Benefits

Implementing a "Forgot Password" feature is vital for enhancing the usability and security of the Bobble AI project. It addresses user concerns about accessing their accounts and improves overall user satisfaction by providing a straightforward and secure process for password recovery. 

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by meghanakn473** [comment]
@mansiruhil13 please assign me this isuue i want to work on it

**Comment by meghanakn473** [comment]
@mansiruhil13 please assign me #241 bcz this issue i hv implemented in other repo

**Comment by mansiruhil13** [comment]
you work on this issue #243 ?

**Comment by meghanakn473** [comment]
> you work on this issue #243 ?

no, ill work on #241
