### ISSUE TITLE
[Feature Request]: Favicon is missing for the website

### ISSUE THREAD

**Issue by kanduru-abhiram** [mansiruhil13/Bobble-AI#244]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Favicon is missing for the website and it would be much better if we have the favicon as the ambulance logo which is in the navbar of website.

### Use Case

Favicon is necessary for any websites that play a key role to find it across many other opened websites in the browser.

### Benefits

Favicon is necessary for any websites that play a key role to find it across many other opened websites in the browser.
Kindly assign me this issue under Hacktoberfest2024.

![image](https://github.com/user-attachments/assets/85f1533e-2922-42d5-8c65-534e37774c06)

### Priority

Medium

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by mansiruhil13** [comment]
assigned already
