### ISSUE TITLE
[Bug]: Sign Up page not visible when clicked on sign up on Login Page

### ISSUE THREAD

**Issue by manikdamle** [mansiruhil13/Bobble-AI#250]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When clicking the Sign Up button on the Login page, the Sign Up page does not appear or load.

### Add Screenshots

![2024-10-06 (1)](https://github.com/user-attachments/assets/31c4560e-e0c3-455e-9e6a-2d0d08f99aa2)
![2024-10-06](https://github.com/user-attachments/assets/eec71ce8-3703-4b4b-918f-bfa5f36a9c27)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by manikdamle** [comment]
I would like to work on this issue pls assign me this @mansiruhil13

**Comment by mansiruhil13** [comment]
> I would like to work on this issue pls assign me this @mansiruhil13

its' done already and working fine
**Screenshots**
![Screenshot 2024-10-06 200246](https://github.com/user-attachments/assets/004310ec-0a1f-45f0-905c-52f4e1c38c1a)
![Screenshot 2024-10-06 200234](https://github.com/user-attachments/assets/762c8179-5a69-4d99-9416-470c9d03f633)
