### ISSUE TITLE
popup message of register email

### ISSUE THREAD

**Issue by VivekShahare04** [mansiruhil13/Bobble-AI#252]
Popup Title: Register Your Email

Message Content: "Thank you for your interest in joining our community! Please enter your email address below to register and receive the latest updates, exclusive offers, and helpful resources straight to your inbox.

Email Input Field:
[Enter your email address]

Buttons:

Submit: By clicking this button, you agree to our terms and privacy policy and confirm that you would like to receive communications from us.
Cancel: Close the popup without registering.
Advantages of the Popup Message:

Clear Call to Action: Encourages users to register their email for updates and offers.
User-Friendly Design: Simple and straightforward layout enhances user experience.
Privacy Assurance: Reinforces trust by mentioning terms and privacy policy.
Immediate Engagement: Captures user interest at the right moment, increasing the likelihood of registration.
Visual Elements:

Include a friendly graphic or icon to make the popup visually appealing.
Use contrasting colors for buttons to enhance visibility.
@mansiruhil13

**Comment by mansiruhil13** [comment]
screenshot??

**Comment by VivekShahare04** [comment]
https://github.com/user-attachments/assets/c3587e26-2468-4cb4-992a-ccad336100f3

I have uploaded a video
here , newslater is subscribe by any mail no notification of subscription or popup or alert is showing how the user will know about it .

Assign me this issue under gssoc and hacktoberfest and level1
I will solve every issue regarding to backend part.
@mansiruhil13

**Comment by mansiruhil13** [comment]
> ezyZip.mp4 
> I have uploaded a video here , newslater is subscribe by any mail no notification of subscription or popup or alert is showing how the user will know about it .
> 
> Assign me this issue under gssoc and hacktoberfest and level1 I will solve every issue regarding to backend part. @mansiruhil13

its' like newsletter functionality. like issue was to print a popup message for thanks for subscribing

**Comment by VivekShahare04** [comment]
changes are made i make an pull request @mansiruhil13

**Comment by mansiruhil13** [comment]
no change in pop up message, because homepage broken issue has been fixed recently, so no change. 

> changes are made i make an pull request @mansiruhil13
