### ISSUE TITLE
Wrong GSSoC label.

### ISSUE THREAD

**Issue by smog-root** [mansiruhil13/Bobble-AI#253]
You have added wrong GSSoC label.

- The label should be gssoc-ext. And add a level(number) label to be more specific about a task. It has only 3 level. 
- All letters as in small case.
- There should not be any space in between!!! 

@mansiruhil13 

#203 #196 (These are just examples) You have added wrong labels for lot of issues!

**Comment by mansiruhil13** [comment]
> You have added wrong GSSoC label.
> 
> * The label should be gssoc-ext. And add a level(number) label to be more specific about a task. It has only 3 level.
> * All letters as in small case.
> * There should not be any space in between!!!
> 
> @mansiruhil13
> 
> #203 #196 (These are just examples) You have added wrong labels for lot of issues!

ok, i am beginner, i have changed now. thankyou.
