### ISSUE TITLE
[Feature Request]: adding pre loader

### ISSUE THREAD

**Issue by solanki505** [mansiruhil13/Bobble-AI#258]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

A pre loader is an essential interface element that appears on a web page while its content is being loaded
I would like to add pre loader to make the web page more interactive

### Use Case

![Screenshot 2024-10-06 172202](https://github.com/user-attachments/assets/6a11a6f7-ae56-47ae-9a39-f049b0cead25)

### Benefits

page more interactive
### Priority

Medium

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by mansiruhil13** [comment]
you can change pre loader design
