### ISSUE TITLE
[Feature Request]:  Add Logo and Tagline to the First Page

### ISSUE THREAD

**Issue by Vishwajeet594** [mansiruhil13/Bobble-AI#26]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description:
The first page is missing a logo and tagline. Adding a logo will give the application a strong brand identity, and a tagline will quickly communicate the app's purpose.

### Proposed Solution:

1. **Add the app's logo at the top of the page.
2. Include a tagline under the logo, e.g., "Connecting Patients, Hospitals, and Drivers for Faster Emergency Care."**

### Priority

Medium

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by ruchikakengal** [comment]
I would like to work on it please label gssoc and hactorbefest accepted @mansiruhil13

**Comment by ChauhanAyush04** [comment]
@mansiruhil13 I would like to work on this project. Please assign me

**Comment by AnujSaha0111** [comment]
I would like to work on it. Can you assign me

**Comment by AnujSaha0111** [comment]
Can you assign it to me, I have also created a pull request, for the same.

**Comment by AnujSaha0111** [comment]
Created a Pull Request to merge
