### ISSUE TITLE
[Bug]: Issue Regarding footer in Team page.

### ISSUE THREAD

**Issue by subin-shk** [mansiruhil13/Bobble-AI#260]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

There is three copy right, all rights resolved in a single team page.
Assign it to me and i'll fix it.

### Add Screenshots

![image](https://github.com/user-attachments/assets/ded8360f-bbfb-4d77-9ee4-60b863773228)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by 345captain** [comment]
i want to work on this issue i think some things need more improvement so can you assign me this issue @mansiruhil13 on the tag of GSSOC-ext
