### ISSUE TITLE
[Feature Request]: Google authorization along  with over all look up of sign up page

### ISSUE THREAD

**Issue by Pri140** [mansiruhil13/Bobble-AI#263]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to make some changes in the login page. The current login page is not that appealing to the end user. I suggest to make it look a bit more authentic , also we can add google's authorization to make the sign up process much easier and fast .
![issue,github](https://github.com/user-attachments/assets/bd72ed62-6891-41ef-8358-35146eef0aba)
This is the link to a mock preview of my suggestion.

### Use Case

let us assume a scenario where a person has an immediate emergency and is in lack of time , the current sign up process needs the user to enter certain details , this is stressful and time taking in a case of emergency. 
Introduction of the one click google authorization will make the sign up process consume very less time and will be easy to use for several user.

### Benefits

It make the app more easy to use .
it decreases time consumption .
one click method will be much faster and easier in case of emergency.

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by mansiruhil13** [comment]
already done.
**Screenshots**
![Screenshot 2024-10-06 200234](https://github.com/user-attachments/assets/07df2747-4257-4b60-beaf-bc427c1e72fb)
![Screenshot 2024-10-06 200246](https://github.com/user-attachments/assets/35043f32-1325-4c02-bd55-f5c7c7298b0f)
