### ISSUE TITLE
[Bug]: Ambuflow logo not visible on  Features, Team, Contact pages navbar

### ISSUE THREAD

**Issue by manikdamle** [mansiruhil13/Bobble-AI#268]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Ambuflow logo not visible on  Features, Team, Contact pages navbar. It should be visible.

### Add Screenshots

![2024-10-06 (6)](https://github.com/user-attachments/assets/8c8509d6-3877-4cbd-89c7-48bbfccf055a)
![2024-10-06 (5)](https://github.com/user-attachments/assets/f9c2339d-431c-4ca8-8d59-af34c59637e6)
![2024-10-06 (4)](https://github.com/user-attachments/assets/89bff14f-a881-49ee-83dd-d7b5f49f0f51)
![2024-10-06 (2)](https://github.com/user-attachments/assets/7c7d6670-9d18-42a7-bb28-1a12e9d07189)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by manikdamle** [comment]
Please assign this issue to me @mansiruhil13

**Comment by mansiruhil13** [comment]
with animation

**Comment by manikdamle** [comment]
Yes will do

**Comment by manikdamle** [comment]
Hi @mansiruhil13 ! I have solved the issue and created an PR #273 for the same. Pls check.
