### ISSUE TITLE
[Feature Request]: Creation of dedicated Contributing.md file & License file along with Updation of README.md

### ISSUE THREAD

**Issue by rajdeepchakraborty-rc** [mansiruhil13/Bobble-AI#269]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## 1. Creation of **Contributing.md** file for Contributors.
Currently, there is no dedicated file for contributors, such as a **Contributing.md**. Instead, the documentation for both the project and contributors is combined within the **README.md** file, which demonstrates poor documentation practices.

I intend to create a separate **Contributing.md** file so that contributors can review the contribution procedure in detail. I also plan to support new contributors by including some git commands and outlining the structure they should follow to contribute effectively to the repository.

## 2. Updating the README.md file for better readability of the users.
Additionally, I want to update the existing **README.md** file to make it more interactive and engaging. I plan to create a separate file named **Screenshots.md** to store all the site’s screenshots, and then add a redirect link to this file from the **README.md** for users to refer to once they are finished reading the **README.md** file. I intend to remove the images from the **README.md** file, as they are causing excessive scrolling, which is becoming an issue. Creating a separate file and adding a redirect will improve the overall readability of the repository.

## 3. Creation of a License file
I will also make a License file [MIT license] for the project.

## 1. Creation of **Contributing.md** file for Contributors.
The new Contributors will find it easy to navigate the required sections.
 
## 2. Updating the README.md file for better readability of the users.
The project will have an overall improved readability and scalability.

## 3. Creation of a License file
The License file is needed in projects that accepts contributions.

## 1. Creation of **Contributing.md** file for Contributors.
This will assist new contributors by providing them with basic git commands and an outline of the structure they should follow to contribute effectively to the repository.

## 2. Updating the README.md file for better readability of the users.
I believe that keeping the **README.md** focused on the project description will enhance the overall quality of the documentation. Additionally, making the **README.md** more engaging and precise will help increase user interaction and activity.

## 3. Creation of a License file
I will help the Contributors know this is an Open-Source project and welcome all contributors to make updates.

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by rajdeepchakraborty-rc** [comment]
I have noticed that you are assigning the wrong labels to the issues. I just wanted to inform you about that and here are the labels that must be assigned:
- **level** (level1 or level2 or level3)
- **gssoc-ext**
- **hactoberfest-accepted**

**Comment by rajdeepchakraborty-rc** [comment]
The gssoc label must be gssoc-ext and not gssoc-extd. Please review that

**Comment by rajdeepchakraborty-rc** [comment]
@mansiruhil13 Thanks for changing the label.
Also wanted to ask one more thing. Should the label not be **level2** for this issue? since I am working on 3 different files in this issue?

**Comment by rajdeepchakraborty-rc** [comment]
Thank You!

**Comment by rajdeepchakraborty-rc** [comment]
@mansiruhil13 while working, I also noticed that you don't have a **license** added to your project! Do you want me to add one? If yes, let me know. I will modify this issue and please do set the level to level3 if you want me to add one!

**Comment by mansiruhil13** [comment]
> @mansiruhil13 while working, I also noticed that you don't have a **license** added to your project! Do you want me to add one? If yes, let me know. I will modify this issue and please do set the level to **level3** if you want me to add one!

okay

**Comment by rajdeepchakraborty-rc** [comment]
I see that you are not much of a talk person and maybe shy.😆
Ok will add it too! 🫡and thanks for the level update

**Comment by rajdeepchakraborty-rc** [comment]
@mansiruhil13 I have updated the title and the description of the issue. You can go through it if you want.

**Comment by rajdeepchakraborty-rc** [comment]
@mansiruhil13 why did you close this? I am still working on it and have not made a PR yet.

**Comment by rajdeepchakraborty-rc** [comment]
Reopen the issue. I am still working on it, and will make a Pull Request(PR) when I am done and inform you.

**Comment by rajdeepchakraborty-rc** [comment]
@mansiruhil13 Can you provide me with a picture of you? Since you don't have one on your GitHub profile. I want to make this in your README.md file:
![image](https://github.com/user-attachments/assets/b3183f86-9f3c-4d40-83a1-98b7599fefc1)
If you allow me then I can use your LinkedIn profile picture. Please try to respond in chat.

**Comment by mansiruhil13** [comment]
why?

**Comment by mansiruhil13** [comment]
yes

**Comment by rajdeepchakraborty-rc** [comment]
Ok will be using your LinkedIn Profile picture then. Thanks for replying 😀

**Comment by rajdeepchakraborty-rc** [comment]
@mansiruhil13 sorry, but can you update your GitHub profile picture to the one on your LinkedIn? Since you have edited out this image from the borders, it is not working good with the code.
https://media.licdn.com/dms/image/v2/D5603AQEoxJoERN7K8Q/profile-displayphoto-shrink_400_400/profile-displayphoto-shrink_400_400/0/1727775831594?e=1733961600&v=beta&t=rnfFOAFuUuDAYpq2a3p9P21MWNHOl81mQG3-wTpGsjM
Can you change your GitHub profile picture to the one on your LinkedIn?

**Comment by mansiruhil13** [comment]
> @mansiruhil13 sorry, but can you update your GitHub profile picture to the one on your LinkedIn? Since you have edited out this image from the borders, it is not working good with the code. https://media.licdn.com/dms/image/v2/D5603AQEoxJoERN7K8Q/profile-displayphoto-shrink_400_400/profile-displayphoto-shrink_400_400/0/1727775831594?e=1733961600&v=beta&t=rnfFOAFuUuDAYpq2a3p9P21MWNHOl81mQG3-wTpGsjM Can you change your GitHub profile picture to the one on your LinkedIn?

update it

**Comment by rajdeepchakraborty-rc** [comment]
Thanks it's done!
![image](https://github.com/user-attachments/assets/429f9a1d-704f-4507-8cfa-5fc386b2fb2f)
Hope you like it.

**Comment by mansiruhil13** [comment]
for any queries.. line you can remove as in readme file, its' already mentioned

**Comment by rajdeepchakraborty-rc** [comment]
I have opened a Pull request #306.

**Comment by rajdeepchakraborty-rc** [comment]
@mansiruhil13 Sorry but I could not understand what you said in the PR chat. Could you explain the issue?

**Comment by rajdeepchakraborty-rc** [comment]
Ok, I understood 1 of the issues. I overlooked changing your name under the LICENSE. That was my fault. I will change that. I think you were asking to put the name AmbuFlow in the LICENSE. Usually the owner's name is added there, but if you want me to add AmbuFlow there, I can do that. I am not sure what you said about the screenshots. Please explain that issue.
