### ISSUE TITLE
Issue in signup page

### ISSUE THREAD

**Issue by Coder-Bhoomi** [mansiruhil13/Bobble-AI#270]
![image](https://github.com/user-attachments/assets/2c9f258e-f627-46d1-89d7-f71197ffd6a9)

1.There is an issue in sign up page i.e. Without filling any details, just clicking on the button gives a pop up message of registration successful.

![image](https://github.com/user-attachments/assets/a01e5602-ed02-4c25-8650-c0e565f23e33)

2. Picture is not arranged in contact us page. Everywhere the picture is in circle shape but on this page it is in square shape.

![image](https://github.com/user-attachments/assets/c785a25c-264a-4533-bd1f-714a2682bc27)

3.  Link is not set in a proper way.

please allow me to make changes.

@mansiruhil13

**Comment by mansiruhil13** [comment]
yes can change on image for google only, rest is correct
