### ISSUE TITLE
[Feature Request]: UI fix needed✨

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [mansiruhil13/Bobble-AI#274]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

there are multiple recurring footer and the footer isnt consistent through different pages as home page is different from other pages.

### Use Case

@mansiruhil13 if you can assign me this ill fix it immediately.
<img width="1460" alt="Screenshot 2024-10-06 at 9 10 06 PM" src="https://github.com/user-attachments/assets/43bafd72-160b-451a-b1f9-432e8310d3d2">
<img width="738" alt="Screenshot 2024-10-06 at 9 16 02 PM" src="https://github.com/user-attachments/assets/8f7f05b1-856f-4cb0-81cc-c2a92656903f">

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by T-Rahul-prabhu-38** [comment]
@mansiruhil13 i was thinking of one more feature

**Comment by T-Rahul-prabhu-38** [comment]
<img width="1460" alt="Screenshot 2024-10-06 at 9 27 02 PM" src="https://github.com/user-attachments/assets/18aa20eb-a4f8-4e48-b295-7ae649cf2d96">
there is no home page here and becasue of that u can not come back to home , shall i work on this feature aswell.

**Comment by mansiruhil13** [comment]
okay, but create with screenshot for output?? so that i can review

**Comment by T-Rahul-prabhu-38** [comment]
ok .can you make it level 2 then

**Comment by T-Rahul-prabhu-38** [comment]
ill work on it

**Comment by mansiruhil13** [comment]
also on signup, (without username and password), account creation successful and returns to home page.. if you want you can work on that also

**Comment by T-Rahul-prabhu-38** [comment]
sure i can do that too
