### ISSUE TITLE
[Feature Request]: Add Help/FAQ and Contact Us Links

### ISSUE THREAD

**Issue by Vishwajeet594** [mansiruhil13/Bobble-AI#28]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description:
The first page does not provide any assistance to users who may need guidance. Adding "Help/FAQ" and "Contact Us" links will ensure users can get support if needed.

### Proposed Solution:

- Add a small "Help/FAQ" button to guide first-time users.
- Add a "Contact Us" link that opens an email form or redirects to a contact page.

### Priority

Medium

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by AhanaGanguly965** [comment]
I am willing to work on this issue.Would u please assign this to me?
