### ISSUE TITLE
[Bug]: Double footer issue

### ISSUE THREAD

**Issue by 4F24L** [mansiruhil13/Bobble-AI#280]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Add Screenshots

![image](https://github.com/user-attachments/assets/6ded9a09-d6c2-492c-826f-b5eda151ffb1)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by 4F24L** [comment]
Which one to keep ? Upper or lower one ?

**Comment by mansiruhil13** [comment]
2nd

**Comment by 4F24L** [comment]
Okay !!
