### ISSUE TITLE
[Feature Request]: FAQ Section Needed

### ISSUE THREAD

**Issue by 4F24L** [mansiruhil13/Bobble-AI#281]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

AmbuFlow should have a FAQ section for user queries.

![image](https://github.com/user-attachments/assets/c8fc7e74-559b-463a-a29c-f8c553adb09e)

### Use Case

- User can understand AmbuFlow better.

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by 4F24L** [comment]
Can you add level 3 to it ? As multiple pages need to be modified for this.

**Comment by 4F24L** [comment]
I'll start working on it by tomorrow. 

So many bugs are there still now. Let's get those fixed first.

**Comment by 4F24L** [comment]
# Addding these questions [ From LinkedIn]

## Safety and Emergency Information:
What should I do while waiting for the ambulance?
How can I contact the ambulance driver directly?
What are the emergency protocols if an ambulance is delayed?
Can I provide medical information for the patient in advance?
How do I report a technical issue with the system?

## Billing and Services:
Are there any charges for using the ambulance tracking service?
How can I view past ambulance service requests?
What payment options are available for ambulance services?
How can I request special medical equipment or personnel on the ambulance?

## How do I track an ambulance in real-time?
What information is required to locate an ambulance?
Can I check the estimated arrival time of the ambulance?
How do I request ambulance assistance from this system?
What areas or locations are covered by the ambulance service?
Is there an option to prioritize emergency cases?
Can I schedule an ambulance in advance?

## System Use Questions:
How do I register or log in to use the ambulance tracking system?
What should I do if the location of the ambulance is not updating?
Can I get notifications when the ambulance is nearby?
Is there a way to track multiple ambulances simultaneously?
How do I cancel a request for an ambulance?

**Comment by 4F24L** [comment]
Creating like this 

https://github.com/user-attachments/assets/5e3d7551-f193-437c-8ac8-0d6424cd366b

**Comment by mansiruhil13** [comment]
i think, ui can be more far better?
