### ISSUE TITLE
[Bug]: "Get Started" Button Redirects to Old Sign-Up Page on Home Page

### ISSUE THREAD

**Issue by ritiksingh-01** [mansiruhil13/Bobble-AI#288]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

On the home page, when clicking the "Get Started" button, the user is redirected to the outdated sign-up page instead of the new one. This creates confusion for users who expect the latest version. I can resolve this issue by updating the link to direct users to the new sign-up page, ensuring smooth navigation.

Additionally, I noticed that the size of the social media links can be improved. I can fix the size and enhance the overall design of the social links for a more cohesive and user-friendly appearance.

Kindly assign this issue to me under the GSSoC'24-Extd and hacktoberfest.

### Add Screenshots

https://github.com/user-attachments/assets/50a1dce7-b77b-441b-96b3-a4f54b7818a6

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by ritiksingh-01** [comment]
Hi, @mansiruhil13 

https://github.com/user-attachments/assets/6928b646-23c2-4dd7-be92-8aebe59fb912


I have successfully resolved the issue where the "Get Started" button on the home page was redirecting to the old sign-up page. Now, it correctly links to the new sign-up page. Additionally, I made several improvements:

- Changed the color of the home button and added hover effects for better interactivity.
- Redesigned and resized the social media icons for a more polished look.
- Added a "locker" button in the password section to toggle visibility, and it is now functioning perfectly.

Please review these changes and allow me to submit a pull request. Given the number of features I’ve implemented, I would also like to request an increase in the issue’s difficulty level to reflect the effort involved.

**Comment by mansiruhil13** [comment]
yes

**Comment by ritiksingh-01** [comment]
> yes

 I request you to kindly  increase the level.

**Comment by ritiksingh-01** [comment]
Hi, @mansiruhil13 
I apologize for the delay with my pull request. As this is my first open-source project, I’m currently working through some conflicts.

I kindly request that you don’t assign this issue to anyone else or merge any related issues until I’ve resolved these conflicts. 

Thank you for your understanding and support!
