### ISSUE TITLE
[Bug]: Home page broken

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [mansiruhil13/Bobble-AI#291]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

home page is broken and ill fix the login too.

### Add Screenshots

<img width="1391" alt="Screenshot 2024-10-06 at 10 26 45 PM" src="https://github.com/user-attachments/assets/94ffa33a-6168-4275-bbe3-68f0628ecbf1">
<img width="1440" alt="Screenshot 2024-10-06 at 10 26 51 PM" src="https://github.com/user-attachments/assets/5bce1f24-73bb-4925-aebb-d9b4a6bc3c44">

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by T-Rahul-prabhu-38** [comment]
brooo

**Comment by T-Rahul-prabhu-38** [comment]
the whole homepage is broken , any ss so i can recreate it?

**Comment by T-Rahul-prabhu-38** [comment]
https://github.com/user-attachments/assets/f63bcb59-0c87-46a6-bde4-fc04a3c1ae7d

**Comment by mansiruhil13** [comment]
![Screenshot 2024-10-06 223253](https://github.com/user-attachments/assets/5420563d-a1c7-42a7-a23a-f581a3d7d5c9)
![Screenshot 2024-10-06 223309](https://github.com/user-attachments/assets/34253d9c-0506-4206-94a3-ad0a7ac90914)
![Screenshot 2024-10-06 223337](https://github.com/user-attachments/assets/d8b23d31-98ee-4acb-9303-79d4b182a41e)
also the text on home is different from features, team and contact

**Comment by 4F24L** [comment]
Can you fix the animation too !! @T-Rahul-prabhu-38

**Comment by T-Rahul-prabhu-38** [comment]
animations of which part.

**Comment by 4F24L** [comment]
> animations of which part.

Preloading animation like this. This was actually working before being broken.
check issue number #277 

https://github.com/user-attachments/assets/3113b2e5-5031-4322-b28e-988c26bcc708

**Comment by T-Rahul-prabhu-38** [comment]
ok.

**Comment by T-Rahul-prabhu-38** [comment]
update:
everything is working as expected ill call a PR now.

**Comment by 4F24L** [comment]
> ok i dont know animations much , ill try other things are fixed. check this
> 
>  Screen.Recording.2024-10-06.at.10.51.25.PM.1.mov

Great work 👏🏻

**Comment by T-Rahul-prabhu-38** [comment]
im facing issue rn the brnach is updated and it has darkmode , but if i push mine that will go

**Comment by T-Rahul-prabhu-38** [comment]
bro ill merge the conflicts and call a PR in 5 mins, please wait till then.

**Comment by 4F24L** [comment]
Okay, no issues. Take your time.

**Comment by T-Rahul-prabhu-38** [comment]
bro i dont think the dark mode feature is working.

**Comment by T-Rahul-prabhu-38** [comment]
im going through the code and i dont see how he has implemented in any page at all.

**Comment by mansiruhil13** [comment]
> bro i dont think the dark mode feature is working.

its' disable

**Comment by T-Rahul-prabhu-38** [comment]
ok. ill push the fixed home page code then?
