### ISSUE TITLE
[Bug]: Duplicate sections

### ISSUE THREAD

**Issue by poorvikaa08** [mansiruhil13/Bobble-AI#292]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I have noticed that there are duplicate sections on the homepage of the website. Specifically, the following sections appear multiple times:
1. Contact us section: This section is repeated twice
2. Footer section is also duplicated
3. Sections containing meet the team and contact us is reapeated twice.

### Add Screenshots

Refer to this video
https://github.com/user-attachments/assets/74935f7a-396a-4a50-a32d-5718ac4dfda1

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by mansiruhil13** [comment]
assigned already

**Comment by mansiruhil13** [comment]
> assigned already

for homepage breakdown issue

**Comment by poorvikaa08** [comment]
@mansiruhil13 Okay I didn't notice as it was created a few minutes back.
I was creating the issue description.

😢

**Comment by mansiruhil13** [comment]
> @mansiruhil13 Okay I didn't notice as it was created a few minutes back. I was creating the issue description.
> 
> 😢

sorry, no issue, if you find any other issue or feature you can add.
