### ISSUE TITLE
[Bug]: incoherent UI for home page

### ISSUE THREAD

**Issue by VaniThapar** [mansiruhil13/Bobble-AI#293]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

1. The home page UI contains unnecessary page breaks
2. Meet our team and contact us info repeated twice
3. Redundant data in the footer. 

Please assign me this issue 

### Add Screenshots

![image](https://github.com/user-attachments/assets/6115fcbf-e44a-4e96-be64-129dc2edcf67)
![image](https://github.com/user-attachments/assets/b607af89-1e3f-427a-b54a-6ba10fac643d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by mansiruhil13** [comment]
assigned already
