### ISSUE TITLE
[Bug]: Fix login and get started button

### ISSUE THREAD

**Issue by poorvikaa08** [mansiruhil13/Bobble-AI#294]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

As you click on the 'Get started' button the user is directed to create your account page.
Also when the user clicks on the 'login' button, it redirects to Sign in page, and in the same page if the user is already registered it redirects to sign-in page.

So there are two sign up pages
![image](https://github.com/user-attachments/assets/0c017f09-a796-483d-8bfe-1b26d5f522fa)
![image](https://github.com/user-attachments/assets/d012b4de-2bf3-490c-93f2-f26a9a7ebea0)

It would be better if we interlink the pages properly.
Also, it would avoid confusion among the users.

I would link this signup page when user clicks on get started and delete the old login page.
![Uploading image.png…]()

### Add Screenshots

Uploading AmbuFlow - Google Chrome 2024-10-06 22-25-27.mp4…

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by mansiruhil13** [comment]
yes, signup page blue one, not greenone

**Comment by ritiksingh-01** [comment]
> yes, signup page blue one, not green one

This issue [#288](https://github.com/mansiruhil13/Bobble-AI/issues/288) has already been assigned to me, and it appears to be a duplicate.
