### ISSUE TITLE
Two Footers Present on the Website

### ISSUE THREAD

**Issue by ShivamTiwari0214** [mansiruhil13/Bobble-AI#298]
The website currently displays two footer sections with slightly different user interfaces. This inconsistency could lead to confusion for users and may impact the overall design cohesion of the site. It would be beneficial to review and unify the footer sections for a more consistent user experience.

![image](https://github.com/user-attachments/assets/bc7bd277-8d78-49b5-a1e5-9bc9f3fd1f01)

@mansiruhil13  please assign this to me.

**Comment by mansiruhil13** [comment]
whole homepage is broken, assigned already
