### ISSUE TITLE
Add Code of Conduct

### ISSUE THREAD

**Issue by anusha7530** [mansiruhil13/Bobble-AI#3]
We recommend that every repo has a code of conduct. If you don’t feel comfortable creating your own Code of Conduct from scratch we highly recommend using one of the templates provided by GitHub. If you do use a template, please read through the template and ensure that you can and will abide by the Code of Conduct.

Please follow these instructions on how to add a Code of Conduct.

Sample: https://github.com/Girlscript-WOB/Guidelines/blob/main/Project%20Admins/Code%20of%20conduct.md

**Comment by nagajaideep** [comment]
can you assign me this issue @anusha7530 @mansiruhil13

**Comment by nagajaideep** [comment]
i have given an pull request could you please review it once

**Comment by nagajaideep** [comment]
hey can you close the issue and add the necessary things on my name so that it would reflect on the WOB'24 page @mansiruhil13 @anusha7530
