### ISSUE TITLE
[Feature Request]: Add Header to the Website

### ISSUE THREAD

**Issue by Vishwajeet594** [mansiruhil13/Bobble-AI#30]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Priority

Medium

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Suhas-Koheda** [comment]
I would like to work upon this issue 
can you assign this to me? @Vishwajeet594

**Comment by Vishwajeet594** [comment]
Hi @mansiruhil13, I hope you're doing well! I wanted to ask if you could please add the appropriate labels to my issues  to help categorize them effectively. Additionally, I noticed that my last pull request, which has already been merged, hasn’t been logged or updated in the records. Could you please add the necessary details and labels for that as well? Thank you for your assistance!

**Comment by shirsakm** [comment]
As no one is currently working on it could I be assigned to this issue?

**Comment by ruchikakengal** [comment]
I like to work on header for the improve navigation and branding @mansiruhil13

**Comment by devarsheecodess** [comment]
Please assign this to me. i can do this for you

**Comment by shirsakm** [comment]
@mansiruhil13 As there seems to be little to no documentation, I just wanted to confirm that this project is built on top of Jekyll?

**Comment by mansiruhil13** [comment]
> @mansiruhil13 As there seems to be little to no documentation, I just wanted to confirm that this project is built on top of Jekyll?

yes

**Comment by devarsheecodess** [comment]
Thank you for assigning this work to me @mansiruhil13 . I wanted to know if this website has a landing page or not. Or should i create one and then create a header?

**Comment by mansiruhil13** [comment]
> Thank you for assigning this work to me @mansiruhil13 . I wanted to know if this website has a landing page or not. Or should i create one and then create a header?

there is no landing page

**Comment by devarsheecodess** [comment]
so on which page do you want the header?

**Comment by devarsheecodess** [comment]
> > Thank you for assigning this work to me @mansiruhil13 . I wanted to know if this website has a landing page or not. Or should i create one and then create a header?
> 
> there is no landing page

so on which page do you want the header?

**Comment by mansiruhil13** [comment]
> > > Thank you for assigning this work to me @mansiruhil13 . I wanted to know if this website has a landing page or not. Or should i create one and then create a header?
> > 
> > 
> > there is no landing page
> 
> so on which page do you want the header?

on landing page?

**Comment by devarsheecodess** [comment]
> > > > Thank you for assigning this work to me @mansiruhil13 . I wanted to know if this website has a landing page or not. Or should i create one and then create a header?
> > > 
> > > 
> > > there is no landing page
> > 
> > 
> > so on which page do you want the header?
> 
> on landing page?

ok sure, i will add one and make the header

**Comment by devarsheecodess** [comment]
![header](https://github.com/user-attachments/assets/5ed603f0-c6bd-4d16-adce-0ba429de4f28)
Done

**Comment by shirsakm** [comment]
I am very confused about the structuring of the program, it uses Jekyll, but has no Gemfile, does not follow Jekyll practices and does not even seem to be using Liquid at all. There is a layout defined in `_layouts` but it is not being used at all. Honestly, the code base needs a complete refactoring, this should probably be an open issue in itself.
