### ISSUE TITLE
[Bug]: Different Sign Up page on Get Started Button

### ISSUE THREAD

**Issue by TeekshaHarish** [mansiruhil13/Bobble-AI#302]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When clicking on the Get Started button it redirects us to a [signup page](https://mansiruhil13.github.io/Bobble-AI/up.html) which is different from the [signup page](https://mansiruhil13.github.io/Bobble-AI/login.html).
Please assign this issue to me under hacktoberfest

### Add Screenshots

![image](https://github.com/user-attachments/assets/0c32cdc9-2a7c-4e8d-b2e1-55b24f4befe3)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by mansiruhil13** [comment]
assigned already
