### ISSUE TITLE
[Feature Request]: Include Footer with Privacy Policy and Terms of Service

### ISSUE THREAD

**Issue by Vishwajeet594** [mansiruhil13/Bobble-AI#31]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Priority

Medium

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by yashksaini-coder** [comment]
can i work on this issue @Vishwajeet594

**Comment by Monalisa0311** [comment]
I also wanted to work on this. can you assign this to me?

**Comment by yashksaini-coder** [comment]
Does we all get same amount of points if we solve this issue ?
@Monalisa0311 @Vishwajeet594 @mansiruhil13

**Comment by Injamul2k24** [comment]
please assign me this issue
