### ISSUE TITLE
[Feature Request]: Implement new font style

### ISSUE THREAD

**Issue by poorvikaa08** [mansiruhil13/Bobble-AI#315]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Change of font style for the entire website.

This is the current font style being used.
![image](https://github.com/user-attachments/assets/229a0d8a-ad4a-4cb9-912d-d647bae137e5)

Suggested font style:
![image](https://github.com/user-attachments/assets/6640f7d9-8965-492f-8392-233c321f1883)

@mansiruhil13 assign it to me.

### Use Case

I would recommend updating the current font style to the Font family: "Poppins", sans-serif that is used in the login page.
It might look great in the entire website.

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by poorvikaa08** [comment]
The website would look like this 👇🏻 
![image](https://github.com/user-attachments/assets/185eb1d2-a2d6-4217-a2d1-efac3d19e5dc)

**Comment by poorvikaa08** [comment]
@mansiruhil13 Let me know if you would like to implement this change

**Comment by SOHAIB-code-png** [comment]
Please assign this issue to me @mansiruhil13
