### ISSUE TITLE
[Bug]: Mobile interface has missing feature 

### ISSUE THREAD

**Issue by HS202022** [mansiruhil13/Bobble-AI#316]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

https://github.com/user-attachments/assets/6f1da39e-68e6-4ed3-9123-6947c572a85f

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by mansiruhil13** [comment]
mobile interface, on mobile also??

**Comment by HS202022** [comment]
> mobile interface, on mobile also??

yess see in mobile we are not getting these options of home , features,team,contact 
![image](https://github.com/user-attachments/assets/8c9cf29b-cd7e-47f7-805d-f63b3bb0506d)

**Comment by mansiruhil13** [comment]
okay

**Comment by HS202022** [comment]
i will do it by tomorrow
