### ISSUE TITLE
[Bug]: Open links in new tab

### ISSUE THREAD

**Issue by AnanteshG** [mansiruhil13/Bobble-AI#317]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When clicking on social links, it opens on the same page, which causes the user to go back. This can be solved by opening the social links in a new tab.

### Add Screenshots

![image](https://github.com/user-attachments/assets/43c3dea1-c0ad-4655-9678-54f76a661d2e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by coderKrysio** [comment]
Hey @mansiruhil13,
is this issue still available?
