### ISSUE TITLE
[Bug]: alignment issue  

### ISSUE THREAD

**Issue by aditiverma18** [mansiruhil13/Bobble-AI#322]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

alignment issue in about.html  
wherein the home , team , feature heading/buttons are not aligned

### Add Screenshots

![Screenshot 2024-10-07 005856](https://github.com/user-attachments/assets/dcd5ac3c-83fe-44c3-aa4c-6ca260c2674d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by mansiruhil13** [comment]
on which page?

**Comment by mansiruhil13** [comment]
i am unable to see

**Comment by 4F24L** [comment]
Can you share the link @aditiverma18

**Comment by aditiverma18** [comment]
https://github.com/mansiruhil13/Bobble-AI/blob/main/about.html
![Screenshot 2024-10-07 011502](https://github.com/user-attachments/assets/d07787a6-942a-4390-a371-9cca875f45b4)
I think the page would look neater if the home , features , teams and contact were aligned and also if they were slightly more centralized just like the log in option below it

**Comment by mansiruhil13** [comment]
its' working fine now
![Screenshot 2024-10-07 012420](https://github.com/user-attachments/assets/f5c7bf03-ea1a-4b7c-bf54-1fdb5340d161)
