### ISSUE TITLE
[Bug]: Two Signup Page Available

### ISSUE THREAD

**Issue by 4F24L** [mansiruhil13/Bobble-AI#323]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## 1st one
![image](https://github.com/user-attachments/assets/69f77a5d-5343-4d09-addc-5c000282bd79)

## 2nd one
![image](https://github.com/user-attachments/assets/1a95b67c-f651-475b-bfad-41b077a344ea)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by 4F24L** [comment]
Which one to keep ??

**Comment by mansiruhil13** [comment]
> Which one to keep ??

blue one, but that's assigned already

**Comment by 4F24L** [comment]
Okay !!
