### ISSUE TITLE
[Feature Request]: Create a new FAQ section

### ISSUE THREAD

**Issue by poorvikaa08** [mansiruhil13/Bobble-AI#330]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Description: The website would benefit from an FAQ (Frequently Asked Questions) section to provide users with quick answers to common questions about the platform. This section could help improve user experience by addressing potential queries and reducing the need for support.

### Use Case

Include common questions such as:
1. What is this platform about?
2. How does this service work?
3. What are the main features?
4. How can users get started?
5. How to contact support?

### Benefits

This section could help improve user experience by addressing potential queries and reducing the need for support.

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by 4F24L** [comment]
This issue is already assigned for me, #281
