### ISSUE TITLE
[Feature Request]: Add Zoom animation on Hover for Footer icons

### ISSUE THREAD

**Issue by rajdeepchakraborty-rc** [mansiruhil13/Bobble-AI#333]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Hover Animations on Footer Icons on Home page
![image](https://github.com/user-attachments/assets/aeba56c7-3518-4925-9898-4bc1a4eabda5)
## Hover Animations on Footer Icons on Contact Us page
![image](https://github.com/user-attachments/assets/803e1f1f-7f7d-4514-8b59-101417efe500)

### Use Case

The users will find it **attractive** and the **usability** of the site will increase, since the icons will be **visually appealing**.

### Benefits

This will make the website more **interactive**.

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Ahsankhalid618** [comment]
@mansiruhil13  can I get to do that? Assign me!

**Comment by rajdeepchakraborty-rc** [comment]
Thanks for assigning. Will start working on it.

**Comment by rajdeepchakraborty-rc** [comment]
@mansiruhil13 Could you assign this to **level2** since I will be working on the Home page as well as the Contact page.

**Comment by rajdeepchakraborty-rc** [comment]
![image](https://github.com/user-attachments/assets/6495844c-96ce-4d55-a44c-9de99eb3b5e5)
Do you want me to remove the names of the social media and keep just the icons in a horizontal manner
Reference image:
![image](https://github.com/user-attachments/assets/794b1f9c-66c9-4915-b534-edc9fecb4ea4)

**Comment by rajdeepchakraborty-rc** [comment]
@mansiruhil13 You have not yet replied. So well I have done the updates on the Contact page. Here is a video:

https://github.com/user-attachments/assets/363fae0d-b142-44fc-908d-b83290035422

The same will be done for the home page. Just read the previous comment and let me know which format you want the icons to be in.

**Comment by rajdeepchakraborty-rc** [comment]
Also I noticed that the options are **not responsive**(the icons are not redirecting to the corresponding websites). Do you want me to work on that issue? If so, please let me know and assign the issue to **level3**

**Comment by rajdeepchakraborty-rc** [comment]
Please do let me know @mansiruhil13 so that I can proceed working on the home page icons.

**Comment by mansiruhil13** [comment]
> Please do let me know @mansiruhil13 so that I can proceed working on the home page icons.

yes

**Comment by rajdeepchakraborty-rc** [comment]
Ok, thanks for the update. Will be adding **responsiveness**, and changing the Home page icons to only logo and removing the texts.

**Comment by rajdeepchakraborty-rc** [comment]
I will let you know about the updates of the work done.

**Comment by rajdeepchakraborty-rc** [comment]
@mansiruhil13 you have merged some broken code. My code had a conflict and the site is broken

**Comment by rajdeepchakraborty-rc** [comment]
@mansiruhil13 I am done with the code but cannot generate a PR due to the broken site from your end(merge conflict)

https://github.com/user-attachments/assets/7c7c62f1-d31a-4e3b-aaab-8939c1e781a2

I am attaching the updated website from my end. I went ahead and added the hover animation to the social icons on all the pages.

**Comment by rajdeepchakraborty-rc** [comment]
@mansiruhil13 I have noticed that you have fixed the site, but again changed the UI of the site(footer). Seems like I have to start working from scratch again. Well no issues! Will go for one more time.

**Comment by mansiruhil13** [comment]
> @mansiruhil13 I have noticed that you have fixed the site, but again changed the UI of the site(footer). Seems like I have to start working from scratch again. Well no issues! Will go for one more time.

yes there are few changes, some of them assigned recently. so do changes in your code according to that.

**Comment by rajdeepchakraborty-rc** [comment]
Yup it will take some time because I have to again start by resolving all the new merge conflicts. Will update you when I am done

**Comment by rajdeepchakraborty-rc** [comment]
Thanks for reviewing the PR!
