### ISSUE TITLE
[Feature Request]: add back to top scroll button at footer

### ISSUE THREAD

**Issue by ananyag309** [mansiruhil13/Bobble-AI#348]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

To improve user experience, especially on longer pages, we can add a "Back to Top" button at the footer. This button will allow users to quickly scroll back to the top of the page without manually scrolling, enhancing navigation and accessibility.

### Use Case

 scroll back to the top of the page without manually scrolling, enhancing navigation and accessibility.

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by genomecrafter** [comment]
Could you please assign this issue to me? I'd like to work on implementing this feature. Thank you!
