### ISSUE TITLE
Issue : Enhance Navbar CSS for Improved User Experience

### ISSUE THREAD

**Issue by ishita-1305** [mansiruhil13/Bobble-AI#352]
The current navbar design could benefit from enhanced styling for better user experience and visual appeal. These can be improved:
-Hover Effects
-Button Styling
-Spacing & Alignment
-Font Sizes
-Responsiveness
![Screenshot 2024-10-07 151441](https://github.com/user-attachments/assets/5358e0fc-f99d-489d-8b71-3fbc6c6af17b)

**Comment by mansiruhil13** [comment]
there is a change in navbar in home only, you can work on this issue:
![Screenshot 2024-10-07 195539](https://github.com/user-attachments/assets/896b1d0d-11d7-4db8-8e11-76ccb825a020)

features team and contact are fine. 
![Screenshot 2024-10-07 195554](https://github.com/user-attachments/assets/37a93bc4-f029-4cba-b773-1908945101ba)
