### ISSUE TITLE
[Bug]: Navbar is not responsive 

### ISSUE THREAD

**Issue by Hemraj-7** [mansiruhil13/Bobble-AI#353]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Navbar is not responsive in mobile devices 

I want to fix this issue assign me

![Screenshot 2024-10-07 154331](https://github.com/user-attachments/assets/156e59d1-a996-4d9e-859f-8522ada48608)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by mansiruhil13** [comment]
only home button ?

**Comment by mansiruhil13** [comment]
> > only home button ?
> 
> Okey other buttons i will remove. first assign me the project

why remove?

**Comment by mansiruhil13** [comment]
they are fine

**Comment by mansiruhil13** [comment]
only issue in clicking on home, otherwise no issue 
https://github.com/user-attachments/assets/e39a261b-cf5f-4ce5-9eba-60111a97d472

**Comment by Hemraj-7** [comment]
> > > only home button ?
> > 
> > 
> > Okey other buttons i will remove. first assign me the project
> 
> why remove?

Remove means hide these buttons like login and get started because they are get extra space in smart phone devices

**Comment by Hemraj-7** [comment]
> they are fine

yeah they are fine but nevbar is not looking good in mobile phone

**Comment by Hemraj-7** [comment]
Hi @mansiruhil13 tell me which one is looking batter 

### with login and get start button
![Screenshot 2024-10-07 210444](https://github.com/user-attachments/assets/78821def-5e5d-4942-bce8-9439303d3e0c)

### without login and get start button
![Screenshot 2024-10-07 211006](https://github.com/user-attachments/assets/4a5e0bc7-9737-45a3-8c32-18c62d8c71d3)

**Comment by mansiruhil13** [comment]
1st

**Comment by Hemraj-7** [comment]
> 1st

thanks for response, also i choose 1st
