### ISSUE TITLE
[Feature Request]: Sign-up improvement

### ISSUE THREAD

**Issue by Aditijainnn** [mansiruhil13/Bobble-AI#356]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

![image](https://github.com/user-attachments/assets/c688a115-b8d0-4c88-b306-e77531c9b90f)
in this sign-up page there is no option for user to go back to home pagge without loging in so adding that button 

### Use Case

Assign this to me under hacktoberfest and gssoc ext

### Priority

Medium

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by ritiksingh-01** [comment]
Hi, @mansiruhil13 

The sign-up improvements have already been implemented, and the feature is functioning as expected. I believe this issue can now be closed.
