### ISSUE TITLE
[Feature Request]:  removal of additional section from the home page

### ISSUE THREAD

**Issue by jyothimanoj12** [mansiruhil13/Bobble-AI#357]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

![Screenshot 2024-10-07 172320](https://github.com/user-attachments/assets/4f3d580a-fdc7-4a1b-88b2-9a52b8d7db4b)
 
![Screenshot 2024-10-07 172328](https://github.com/user-attachments/assets/1a18d5dc-2d78-4d97-8932-5eec0270f608)

i dont think this section is neccessary  , we already have these options on the navbar . instead we can do something like this

![Screenshot 2024-10-07 173028](https://github.com/user-attachments/assets/4ea70823-c8a4-4ff2-8579-340c77e50511)

plz assign me this issue under gsoc-ext , hacktober-accepted, level 2 tags

### Use Case

the home page would look more organized

### Priority

Medium

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by mansiruhil13** [comment]
what? can you elaborate? i can't see any issue?

**Comment by jyothimanoj12** [comment]
> what? can you elaborate? i can't see any issue?

Contact us and meet the team are not necessary as its already in the navbar , the page will look more cluttered

**Comment by mansiruhil13** [comment]
> > what? can you elaborate? i can't see any issue?
> 
> Contact us and meet the team are not necessary as its already in the navbar , the page will look more cluttered

i think, there is no need. its' fine. if you remove team and contact then there are only home features and feedbacks options available left.

**Comment by jyothimanoj12** [comment]
> > > what? can you elaborate? i can't see any issue?
> 
> > 
> 
> > Contact us and meet the team are not necessary as its already in the navbar , the page will look more cluttered
> 
> 
> 
> i think, there is no need. its' fine. if you remove team and contact then there are only home features and feedbacks options available left. 

Not from the navbar / menu , i was taking about the the contact and teams links given at the bottom of the page , it makes the page looks cluttered

**Comment by jyothimanoj12** [comment]
[![image](https://github.com/user-attachments/assets/5a51fd30-05a0-42a8-b0dc-4ce6ab45f4dd)]()

This is how the page would look like without the contact and team section at bottom, which looks less cluttered

**Comment by mansiruhil13** [comment]
i think there is no need
