### ISSUE TITLE
[Bug]: AmbuFlow Logo hover effect issue

### ISSUE THREAD

**Issue by 4F24L** [mansiruhil13/Bobble-AI#360]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Logo should not contain hover effect
- There was an hover effect on landing page on the brand logo and the brand name; this should not happen to keep the website's UI standard.

### Add Screenshots

https://github.com/user-attachments/assets/92b1c850-53e2-431e-bae7-a2f57b0cdcee

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by mansiruhil13** [comment]
assigned already
