### ISSUE TITLE
[Feature Request]: adding chatbot✨

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [mansiruhil13/Bobble-AI#364]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

adding chatbot so people can have a general idea over some symptons.

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by T-Rahul-prabhu-38** [comment]
@mansiruhil13 if u can assign me this task ill work on it.

**Comment by mansiruhil13** [comment]
assigned already
