### ISSUE TITLE
[Feature Request]: Feedback Textarea is going outside of the parent box 

### ISSUE THREAD

**Issue by milanroy704** [mansiruhil13/Bobble-AI#366]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Need to add the width of the textarea of the feedback page 
![image](https://github.com/user-attachments/assets/7ee2620f-e24f-463d-a710-053423092e0c)

### Use Case

For User Engagement

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC contributor
- [X] I want to work on this issue
- [ ] I'm willing to provide further clarification or assistance if needed.

**Comment by 4F24L** [comment]
Please sync your fork with the latest commits.

https://mansiruhil13.github.io/Bobble-AI/Feedback.html

There is no issue like that you mentioned.
