### ISSUE TITLE
[Bug]: Improve the icon image in contact page

### ISSUE THREAD

**Issue by Subhajit-2023-44** [mansiruhil13/Bobble-AI#370]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![Screenshot 2024-10-07 221155](https://github.com/user-attachments/assets/70526262-a3a7-40f8-aa56-1a459bcf3dff)
The icon image in the "Need Help?" section of the contact page doesn't look very good.   I want to improve icon image width properly.   @mansiruhil13 please assign me this task.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by 4F24L** [comment]
Make the images round like other pages.

Refer this link :
https://mansiruhil13.github.io/Bobble-AI/index.html
