### ISSUE TITLE
[Feature Request]:  Enhance the footer colour

### ISSUE THREAD

**Issue by poorvikaa08** [mansiruhil13/Bobble-AI#371]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The current footer background colour is grey
![image](https://github.com/user-attachments/assets/662ad56f-0dc2-4ab2-8d10-226c5f2372e1)

It would be better if we implement new colour to which matches the colour paletter of the website

### Use Case

I would like to enhance its design by changing its color as below which matches the entire color palette of the website.
![image](https://github.com/user-attachments/assets/6743ee37-7a57-4b2c-a9c5-602ea3516c17)

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by 4F24L** [comment]
If you change like this !!

You have to change the footer of all pages. @poorvikaa08

**Comment by poorvikaa08** [comment]
@mansiruhil13 assign this issue to me
