### ISSUE TITLE
[Bug]: Missing Hover effect in Sign-up & subscribe button

### ISSUE THREAD

**Issue by Deepak0yadav** [mansiruhil13/Bobble-AI#374]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

 **Hover effect** is missing in Sign-up and subscribe button . We should add the feature for the better User experience.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by mansiruhil13** [comment]
example? can you elaborate? (with screenshot/ idea/ design)

**Comment by Deepak0yadav** [comment]
![Screenshot 2024-10-08 015803](https://github.com/user-attachments/assets/d221096a-8e7c-4d32-99ce-d685e583acad)
Here Subscribe button is not having the Hover effect
![Screenshot 2024-10-08 015829](https://github.com/user-attachments/assets/6172be24-7f98-4af0-8829-f280ee1cf8a8)
Sign button is also having this issue

**Comment by harshbhar0629** [comment]
Can i work on this issue??

**Comment by mansiruhil13** [comment]
> Can i work on this issue??

assigned already

**Comment by Deepak0yadav** [comment]
Ya ,I am working on it
