### ISSUE TITLE
[Bug]: Feedback 405 error

### ISSUE THREAD

**Issue by 4F24L** [mansiruhil13/Bobble-AI#375]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

405 error on feedback page

https://github.com/user-attachments/assets/da223485-6e46-40f6-b717-af98e2f54269

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by poorvikaa08** [comment]
@4F24L 
How can you self assign this issue?

**Comment by 4F24L** [comment]
> @4F24L 
> How can you self assign this issue?

She asked me to fix that issue. And she wasn't available when the issue was being raised.
