### ISSUE TITLE
[Bug]: Ambuflow Logo

### ISSUE THREAD

**Issue by poorvikaa08** [mansiruhil13/Bobble-AI#380]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The logo in the README.md file has the old logo, it has to be updated.

### Add Screenshots

![image](https://github.com/user-attachments/assets/5dbb96a4-077e-4f82-8350-f577bde0f813)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by poorvikaa08** [comment]
@mansiruhil13 
If this is the main logo, then the logo in the current website has to be changed

**Comment by poorvikaa08** [comment]
Which is the main logo?
![image](https://github.com/user-attachments/assets/22743880-6c48-4d42-a979-2e2a17d1d807)
![image](https://github.com/user-attachments/assets/fe4358fe-c7bf-485f-890a-5041bb5d61ea)

**Comment by poorvikaa08** [comment]
@mansiruhil13 ??

**Comment by mansiruhil13** [comment]
1st one is for website and 2nd one for github readme file, but you can put 1st one
