### ISSUE TITLE
[Bug]: Home page fix

### ISSUE THREAD

**Issue by poorvikaa08** [mansiruhil13/Bobble-AI#382]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In the home page, the header section and the info is broken.

Changes to be made:
* Fix header - as the header looks too small, it has to be fixed
* In the info section, there's a gap in right most side (Improper alignment)

I will fix this issue

### Add Screenshots

![image](https://github.com/user-attachments/assets/cb2f66d5-2149-4708-939f-1e09b76e9fc3)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by poorvikaa08** [comment]
Also in the nav bar, the header size is the same as the button size in it.

**Comment by mansiruhil13** [comment]
yes noticed, homepage have broken many times.
![Screenshot 2024-10-08 013427](https://github.com/user-attachments/assets/c895a98a-c598-4191-8ddb-ba52ba4ec96a)

**Comment by poorvikaa08** [comment]
@mansiruhil13 You can assign level 3 as it has to be fixed in every single page

**Comment by poorvikaa08** [comment]
![image](https://github.com/user-attachments/assets/48a31116-623f-4ca0-b9ef-6123daf79596)

It's even worse now 🤣

**Comment by mansiruhil13** [comment]
> @mansiruhil13 You can assign level 3 as it has to be fixed in every single page 😢 

I will add label by the morning.  There is a network problem.

**Comment by mansiruhil13** [comment]
> ![image](https://private-user-images.githubusercontent.com/152640996/374321145-48a31116-623f-4ca0-b9ef-6123daf79596.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzNjY0MzMsIm5iZiI6MTcyODM2NjEzMywicGF0aCI6Ii8xNTI2NDA5OTYvMzc0MzIxMTQ1LTQ4YTMxMTE2LTYyM2YtNGNhMC1iOWVmLTYxMjNkYWY3OTU5Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwOFQwNTQyMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZGE0ODdlOTY4ODFlNGFjOWZkMjc4NjM5MGVmMGNmMmE2ZThhMmU1NzA3ODlhZjRhNzgxYWNmZTI0YzM2YjE1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.sIWruzeU99fn8P48gt78IeCVJUCJXSnZHgPvFI0vxcs)
> 
> It's even worse now 🤣

features and teams page also in the homepage. only home has been fixed.
