### ISSUE TITLE
[Bug]: Broken pages

### ISSUE THREAD

**Issue by poorvikaa08** [mansiruhil13/Bobble-AI#387]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The feature page and team page broken.
This issue probably happened during the addition of cursor animation.

### Add Screenshots

![image](https://github.com/user-attachments/assets/3644a1ca-cf06-4758-bc7c-535b2a05505a)
![image](https://github.com/user-attachments/assets/1caedd5d-d064-48fd-b577-ba59500071d1)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by 4F24L** [comment]
Don't make a PR before assigning the issue. @poorvikaa08 

Look carefully at every PR before merging @mansiruhil13 .

**Comment by poorvikaa08** [comment]
@mansiruhil13 
I have raised the issue then requested the PR, assign me to this then you can merge it.
