### ISSUE TITLE
[Feature Request]: Add Blue Cursor Tail Effector for Enhanced User Experience

### ISSUE THREAD

**Issue by ritiksingh-01** [mansiruhil13/Bobble-AI#394]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I propose adding a blue cursor tail effector to improve the overall user experience. This subtle but visually appealing effect will make interactions feel more dynamic and engaging for users, enhancing the visual feedback as they navigate through the site.

Kindly assign this issue to me under GSSoC-Extd and Hacktoberfest.

### Use Case

The blue cursor tail effector enhances the user experience by providing dynamic visual feedback as users navigate the website. When the user moves their cursor, a subtle blue trail follows, creating a more engaging and interactive feel. This effect improves the visual appeal of the site and encourages interaction with buttons and links, making the overall navigation smoother and more enjoyable. By adding this feature, the website becomes more visually pleasing and interactive, without being intrusive or affecting performance.

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by ritiksingh-01** [comment]
Hi, @mansiruhil13 

I think the cursor effect would be best suited for the home page only, as it adds a playful and engaging touch for first-time visitors. By limiting the effect to the home page, the other sections, such as the profile or more content-heavy pages, can retain a clean and professional look. This balance will help maintain a polished user experience, where the home page feels interactive and welcoming, while the rest of the site preserves a more formal and business-like atmosphere, ensuring that the profile remains professional and doesn't feel overly stylized.

**Comment by mansiruhil13** [comment]
yes
