### ISSUE TITLE
Make navbar sticky and clicking on logo will direct to home page

### ISSUE THREAD

**Issue by jvkousthub** [mansiruhil13/Bobble-AI#396]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The navbar  of the home page can be made sticky and it remains there throughout the scroll
clicking in the logo should take to home page

### Use Case

Make the project more good looking

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by jvkousthub** [comment]
@mansiruhil13 Assign me this issue

**Comment by mansiruhil13** [comment]
ambuflow also included in logo and 2nd thing navbar section broken?
![Screenshot 2024-10-08 121900](https://github.com/user-attachments/assets/25129156-2d18-41d8-99a1-0a25b94e6cd8)
