### ISSUE TITLE
[Bug]: Footer not responsive in smart phones

### ISSUE THREAD

**Issue by Hemraj-7** [mansiruhil13/Bobble-AI#399]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

[Bug]: Footer not responsive in smart phones footer is take extra width in the website

![Screenshot 2024-10-08 114019](https://github.com/user-attachments/assets/b651caaa-a43f-4ee2-9b36-1861548d94b3)

assign me @man

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by mansiruhil13** [comment]
footer section for newsletter assigned recently

**Comment by Hemraj-7** [comment]
> footer section for newsletter assigned recently

please tell me issue number

**Comment by mansiruhil13** [comment]
#398

**Comment by Hemraj-7** [comment]
> #398

okey thank you 

if you have any html css related issue please assign me
