### ISSUE TITLE
Clumsy buttons on the home page

### ISSUE THREAD

**Issue by Sravanthi1664** [mansiruhil13/Bobble-AI#402]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

![image](https://github.com/user-attachments/assets/48ac4908-0a1b-4531-a1b8-446cb6340752)

![image](https://github.com/user-attachments/assets/683b44cc-0afc-45ef-9539-140bfe42a476)

### Use Case

As you can see, the login and signup buttons should be in the top right of the website for efficiency and not be along with the other buttons which makes it clumsy.

### Benefits

Easy accessing and good finish to the website.

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Sravanthi1664** [comment]
@mansiruhil13 assign me this work.

**Comment by mansiruhil13** [comment]
> @mansiruhil13 assign me this work.

already done
