### ISSUE TITLE
[Bug]: Double Newsletter in Footer

### ISSUE THREAD

**Issue by 4F24L** [mansiruhil13/Bobble-AI#405]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/user-attachments/assets/1552ebbf-ef3b-42a0-865b-32216916657f)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by mansiruhil13** [comment]
assigned already #398
