### ISSUE TITLE
[Feature Request]: About us html page enhancement

### ISSUE THREAD

**Issue by Ananya-vastare** [mansiruhil13/Bobble-AI#407]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The about us page palette was to dull which made it a little difficult to read so I would like to enhance/improvise  the about us page 

### Use Case

The following features that require enhancement are:
1)The logo
2)The background color
3) The header
4)The aligment of the content of the body

### Benefits

Enhancing the logo improves brand identity and recognition, making a strong first impression. Upgrading the background color enhances aesthetic appeal, readability, and emotional impact. A polished header improves navigation ease and contributes to a professional look. Proper alignment of body content enhances clarity, organization, and user engagement. Overall, these enhancements lead to a better user experience, increased conversion rates, and improved accessibility.

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by mansiruhil13** [comment]
any screenshot or idea??

**Comment by Ananya-vastare** [comment]
![Change15](https://github.com/user-attachments/assets/74ca1c8b-e59f-4c71-aefc-4254a75c74b4)
The header needs to get completed I have done half here

**Comment by Ananya-vastare** [comment]
If I can go ahead can you please mention the level of this thank you

**Comment by mansiruhil13** [comment]
![Screenshot 2024-10-08 131900](https://github.com/user-attachments/assets/25546fe7-c35b-49a6-8051-4f99e73e6eca)
i think, no need to change

**Comment by Ananya-vastare** [comment]
@mansiruhil13  may I know why was this closed

**Comment by mansiruhil13** [comment]
> @mansiruhil13 may I know why was this closed

no need to change, its' done already

**Comment by mansiruhil13** [comment]
> Hoe may I please know



> ![Screenshot 2024-10-08 131900](https://private-user-images.githubusercontent.com/157950124/374460501-25546fe7-c35b-49a6-8051-4f99e73e6eca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzNzQ3ODEsIm5iZiI6MTcyODM3NDQ4MSwicGF0aCI6Ii8xNTc5NTAxMjQvMzc0NDYwNTAxLTI1NTQ2ZmU3LWMzNWItNDlhNi04MDUxLTRmOTllNzNlNmVjYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwOFQwODAxMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMTIxOGY3YWFiMTk5NDNlMjcyMmRlOWEwOWY5M2FhMTY1NWFlNmU5ZWY2MmU2ZTgzNzdjZGY0MGQwYjc3NTQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Zj3Cu26ZnCm0J8qU1AwxKfAGL3k8SWkqO277rOIwmNM) i think, no need to change

..

**Comment by Ananya-vastare** [comment]
I have enhanced this to this 
![Change16](https://github.com/user-attachments/assets/32fc3f15-5d2f-44e2-a297-83b073bbd889)
Because the logo is different in most of the pages and also the palette

**Comment by mansiruhil13** [comment]
> > Hoe may I please know
> 
> > ![Screenshot 2024-10-08 131900](https://private-user-images.githubusercontent.com/157950124/374460501-25546fe7-c35b-49a6-8051-4f99e73e6eca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzNzQ3ODEsIm5iZiI6MTcyODM3NDQ4MSwicGF0aCI6Ii8xNTc5NTAxMjQvMzc0NDYwNTAxLTI1NTQ2ZmU3LWMzNWItNDlhNi04MDUxLTRmOTllNzNlNmVjYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwOFQwODAxMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMTIxOGY3YWFiMTk5NDNlMjcyMmRlOWEwOWY5M2FhMTY1NWFlNmU5ZWY2MmU2ZTgzNzdjZGY0MGQwYjc3NTQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Zj3Cu26ZnCm0J8qU1AwxKfAGL3k8SWkqO277rOIwmNM) i think, no need to change
> 
> ..

but logo is coorect in this

**Comment by mansiruhil13** [comment]
if you find any other issue or feature, you can work on that issue

**Comment by mansiruhil13** [comment]
> I have enhanced this to this ![Change16](https://private-user-images.githubusercontent.com/116643029/374465781-32fc3f15-5d2f-44e2-a297-83b073bbd889.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzNzUzMzAsIm5iZiI6MTcyODM3NTAzMCwicGF0aCI6Ii8xMTY2NDMwMjkvMzc0NDY1NzgxLTMyZmMzZjE1LTVkMmYtNDRlMi1hMjk3LTgzYjA3M2JiZDg4OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwOFQwODEwMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NTc2MzQ4YjRjZTI0MDI1YTBiYzZjNmRkZGMzNTI3ZTUyNWYzMWY0MjFkZDg5ZmJkMTU1ODYwMGY5ZjNhYjE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.qs9BeucbmRjcz_OE0OjtL18Y_FIETflEq6i2lFnaT2s) Because the logo is different in most of the pages and also the palette

this logo has been changed now
