### ISSUE TITLE
[Bug]: Navbar is creating issue in pc version

### ISSUE THREAD

**Issue by Hemraj-7** [mansiruhil13/Bobble-AI#409]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Yesterday navbar is fine. but now it is looking ugly 

In the small devices it is looking good but in the pc version looking bad

![Screenshot 2024-10-08 130336](https://github.com/user-attachments/assets/850b6875-d200-448f-852a-69d4f4391e93)

ill make responsive in both devices (small devices and pc version)

assign me 

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by mansiruhil13** [comment]
assigned already
