### ISSUE TITLE
[Feature Request]: add password eye button

### ISSUE THREAD

**Issue by ChauhanAyush04** [mansiruhil13/Bobble-AI#42]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Add password eye button in login and signup page for checking password

### Use Case

user can see their password if they have filled it right or not.

### Priority

Medium

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [ ] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by devarsheecodess** [comment]
Please assign this to me with gssoc-extd label. i can do this for you

**Comment by Devanshu1603** [comment]
please assign me this issue under gssoc-ext label

**Comment by Injamul2k24** [comment]
please assign me this issue

**Comment by devarsheecodess** [comment]
@mansiruhil13 I have fixed this issue and have raised the PR. plz check and merge accordingly.

**Comment by devarsheecodess** [comment]
@mansiruhil13 i have fixed the issue and have raised a PR. check and merge accordingly.

**Comment by Devanshu1603** [comment]
can i generate a new pull request

**Comment by mansiruhil13** [comment]
> can i generate a new pull request

yes

**Comment by Shukla000** [comment]
please assign me this task
