### ISSUE TITLE
[Bug]: The cursor is not uniform through out the website

### ISSUE THREAD

**Issue by ananyag309** [mansiruhil13/Bobble-AI#421]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

home feature and team page have similar cursor whereas feedback and contact page have different cursor. Need to have a similar cursor throughout the website

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by kunal649** [comment]
@mansiruhil13 you can assign me any issue, I'm up for any contribution & how about connecting at linkedin?

**Comment by mansiruhil13** [comment]
> @mansiruhil13 you can assign me any issue, I'm up for any contribution & how about connecting at linkedin?

assigned already

**Comment by kunal649** [comment]
u didnt .. all issues are assigned to guys i dont even know

**Comment by mansiruhil13** [comment]
> u didnt .. all issues are assigned to guys i dont even know

?

**Comment by kunal649** [comment]
I'm saying you can assign me any issue ...i'm interested to contribute. or can i work on issues that are altready assigned 
to someone?

**Comment by mansiruhil13** [comment]
> I'm saying you can assign me any issue ...i'm interested to contribute. or can i work on issues that are altready assigned to someone?

you can create an issue
