### ISSUE TITLE
[Bug]: Improve the button color 

### ISSUE THREAD

**Issue by Subhajit-2023-44** [mansiruhil13/Bobble-AI#430]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

when you open the tab the buttons color changes -
"feedback" tab - the button color is white, 
"contact" tab - the button color is black, 
"team" tab -  the button color is white, 
"features" tab - the button color is black, 
& "home" tab - the button color is blue.. which doesn't look very good. I want to change the color of all tabs to blue color and also fix the main problem - when I open the "home" tab the color of the both 'home" and "features" tab button changes from white to blue.

![Screenshot 2024-10-08 165148](https://github.com/user-attachments/assets/c4d6a8ff-ae94-4e25-91bc-bbe76c384204)

@mansiruhil13  please assign me this task.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Subhajit-2023-44** [comment]
@mansiruhil13

**Comment by mansiruhil13** [comment]
assigned already
