### ISSUE TITLE
[Feature Request]: Updating the footer section 

### ISSUE THREAD

**Issue by Abhi9shinde** [mansiruhil13/Bobble-AI#433]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

There is no proper spacing of the elements in the footer section, so I would like to update it.
![Screenshot 2024-10-08 191714](https://github.com/user-attachments/assets/13d82399-0a9a-4a83-b71f-735d20eb5919)

### Use Case

This will make the page look more appealing

### Priority

Medium

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by mansiruhil13** [comment]
there is breakdown of footer
![Screenshot 2024-10-08 231852](https://github.com/user-attachments/assets/2af55b67-6815-41d1-92ff-5ae84871ce61)
but its' assigned already

**Comment by Abhi9shinde** [comment]
ok maam, I'll look for another issue
