### ISSUE TITLE
[Bug]: Please add hactoberfest topic in your repo,

### ISSUE THREAD

**Issue by rishyym0927** [mansiruhil13/Bobble-AI#44]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

[Bug]: Please add hactoberfest topic in your repo, Our pr will not be counted then

### Add Screenshots

![image](https://github.com/user-attachments/assets/05c2e9bf-48ca-4993-8dcf-b5271c779289)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by mansiruhil13** [comment]
how to add? I have no idea

**Comment by shirsakm** [comment]
> how to add?

You have to add the topic `hacktoberfest` (not `hactoberfest` as the verification process is automatic) and add the `hacktoberfest-accepted` label for valid PRs. Please find more information [here](https://startup-cto.net/preparing-your-repositories-for-hacktoberfest/) and at the ["Maintainers" section at the official website](https://hacktoberfest.com/participation/).
