### ISSUE TITLE
[Feature Request]: Add Driver Performance Monitoring

### ISSUE THREAD

**Issue by pavitraag** [mansiruhil13/Bobble-AI#441]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Monitor ambulance driver behavior (e.g., speed, sharp turns) to ensure safety during patient transport.

### Use Case

Benefits:
Enhanced Safety: Continuous monitoring ensures that drivers operate within safe driving practices.
Improved Accountability: Provides transparency and accountability for drivers' performance during emergency situations.
Regulatory Compliance: Ensures compliance with road safety standards, reducing potential legal and insurance issues.
Performance Insights: Data-driven insights help in training and improving driver behavior, leading to safer patient transport experiences.

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by mansiruhil13** [comment]
with proper ui
