### ISSUE TITLE
[Feature Request]:  Implement Signup and Login (backend)

### ISSUE THREAD

**Issue by devarsheecodess** [mansiruhil13/Bobble-AI#443]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Backend is not yet created for this website, so i will create an express js app and work on implementing login and signup. I will write the entire logic, comment it which should be uncommented when the PA creates a mongo DB server and configures it in the server as i cant create the DB (it should be created only by project admin for security purposes). I will also use bcrypt js and jwt.

### Use Case

Users will be able to create an account and login easily. 

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by kunal649** [comment]
@devarsheecodess Ok first you go for it and notify plz ... im also ready for some backend logic too :) Waiting for update from your side.

**Comment by mansiruhil13** [comment]
> @devarsheecodess Ok first you go for it and notify plz ... im also ready for some backend logic too :) Waiting for update from your side.

for example? can you elaborate with screenshot

**Comment by devarsheecodess** [comment]
The website has hardcoded username and password, but we have to give an option for users to signup and select their desired username and password.
I will create an express app for backend which is based on javascript, for users to login and signup. 

brcypt js is an NPM package which hashes the passwords and keeps them secured i.e the actual passwords are not visible in the database.

JWT means json web token, it is used to handle sessions.

But for that we need mongo DB and mongo DB cluster should be created only by the project owner. 
We can do one thing, first you can create a mongo DB database and add the connection string and then i can work on this task, it will be better. 
Without mongo, i wont be able to test whether my logic is correct or not. I didnt think of this problem before...
