### ISSUE TITLE
Missing Validation in Newsletter , SignUp Page, and Login Page | Text Justification | BackToTop Scrolling Issue and .......

### ISSUE THREAD

**Issue by Shariq2003** [mansiruhil13/Bobble-AI#444]
On the website, multiple fixes are required like : 
1. Newsletter Email validation.
2. Newsletter Success/Failure Popup Alert Missing.
3. BackToTop Button Hard scroll to the top without smooth scrolling.
4. Text Justification is not there in home page cards.
Also, refer to this video.

https://github.com/user-attachments/assets/4b436673-21b7-4cd6-8a49-61ae957af155

Please assign this to me.

**Comment by mansiruhil13** [comment]
you can work but there is issue in navbar section that's assigned already, you have to make changes according to that
![Screenshot 2024-10-08 225227](https://github.com/user-attachments/assets/4320c197-366c-466e-81b8-d232a41eaf13)
![Screenshot 2024-10-08 230037](https://github.com/user-attachments/assets/d1782277-1f43-4c91-9213-f863987f4c74)
![Screenshot 2024-10-08 230212](https://github.com/user-attachments/assets/636f1c77-220e-425d-a127-8088bee02647)

**Comment by Shariq2003** [comment]
> you can work on this issue but there is issue in navbar section that's assigned already, you have to make changes according to that ![Screenshot 2024-10-08 225227](https://private-user-images.githubusercontent.com/157950124/374667079-4320c197-366c-466e-81b8-d232a41eaf13.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0MTAyMDksIm5iZiI6MTcyODQwOTkwOSwicGF0aCI6Ii8xNTc5NTAxMjQvMzc0NjY3MDc5LTQzMjBjMTk3LTM2NmMtNDY2ZS04MWI4LWQyMzJhNDFlYWYxMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwOFQxNzUxNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YjFjYzY4NGU2NTU2MmZmMThmYTQyMGUyNDkwNDFmNGVmN2M0MjA1MzhjYTZkYjFiODJiZTdlNmVmNTUwNjNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.qg1ydULpKdGjkmMWRstUT5p55P7f1BCOdkZ__e8_-Rw) ![Screenshot 2024-10-08 230037](https://private-user-images.githubusercontent.com/157950124/374667091-d1782277-1f43-4c91-9213-f863987f4c74.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0MTAyMDksIm5iZiI6MTcyODQwOTkwOSwicGF0aCI6Ii8xNTc5NTAxMjQvMzc0NjY3MDkxLWQxNzgyMjc3LTFmNDMtNGM5MS05MjEzLWY4NjM5ODdmNGM3NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwOFQxNzUxNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YzZhMWEwYzlmY2E3MjU5MWFlNmUzMWNiNWJhNjJlOWZjOWQ1YThkN2MzNzdhNzA2OGRhODMzM2YzMzhkODc4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Jwy4LvY--CXZtONijBH4Pa5991dN2zd2jAa5asl7Xww) ![Screenshot 2024-10-08 230212](https://private-user-images.githubusercontent.com/157950124/374667096-636f1c77-220e-425d-a127-8088bee02647.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0MTAyMDksIm5iZiI6MTcyODQwOTkwOSwicGF0aCI6Ii8xNTc5NTAxMjQvMzc0NjY3MDk2LTYzNmYxYzc3LTIyMGUtNDI1ZC1hMTI3LTgwODhiZWUwMjY0Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwOFQxNzUxNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZWQxNjcwYTI1MmJlMzM3ZmViYTYxYTAyZDA5NDMyZmRjNmFmNTAyZjlhNzhlYzY2ZGEzNjNiZDg2ODI5ZGE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.RBl9DDDwdqqfaP9jVHPY4ZJeiDpynTEdDppuJkfBWMM)

okay mama

**Comment by mansiruhil13** [comment]
actually whole home page broken assigned already, make changes for newsletter, signup .. according to that. so that when other pr merged, this issue will not create any other issue again.

**Comment by Shariq2003** [comment]
> actually whole home page broken assigned already, make changes for newsletter, signup .. according to that. so that when other pr merged, this issue will not create any other issue again.

okay @mansiruhil13

**Comment by Shariq2003** [comment]
> actually whole home page broken assigned already, make changes for newsletter, signup .. according to that. so that when other pr merged, this issue will not create any other issue again.

@mansiruhil13 still the main branch consist of two many bugs in the website

**Comment by Shariq2003** [comment]
Should i continue to resolve my issue or wait for a stable edition of main page

**Comment by Shariq2003** [comment]
Well home page does not have such issues now, so I can proceed to resolve to my proposed issues.

**Comment by Shariq2003** [comment]
Now i am working on this as the main branch is stable now

> actually whole home page broken assigned already, make changes for newsletter, signup .. according to that. so that when other pr merged, this issue will not create any other issue again.

Now i am working on this as the main branch is stable now

**Comment by Shariq2003** [comment]
@mansiruhil13 please review and merge.

**Comment by Shariq2003** [comment]
@mansiruhil13 mam, now u can merge my PR

**Comment by Shariq2003** [comment]
@mansiruhil13 mam, please review again and merge my PR
