### ISSUE TITLE
[Feature Request]: Updating login page

### ISSUE THREAD

**Issue by Tanyashri** [mansiruhil13/Bobble-AI#45]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Currently the login page is not organised well, also it has no social media login option.
I'd like to contribute by making some changes in the login page using html and css  by adding social media login option and making slight changes in the design of the login page.

### Use Case

It's necessary to have social media login option as it makes the login simpler for the user and enhances the project overlook. 

### Benefits

Adding social media login option helps the user to login easily and makes it simple rather than entering the details over and over again. Login page is the outlook of the entire application so adding basic necessary features is a must.
Thank you
 @mansiruhil13 

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by jvkousthub** [comment]
@Tanyashri I would like to work on this issue, can you please assign me this

**Comment by jvkousthub** [comment]
@mansiruhil13 I would like to work on this issue can you assign me this

**Comment by Kameshnic** [comment]
can i work on this issues kidnly assign me with gsoc level adn then hacktoberfest lable s

**Comment by leharikasri** [comment]
@mansiruhil13 i would love to work on this too,can u assign it to me

**Comment by dsasa89** [comment]
I would also love to do this project so i can be done my first contribution . Thank you
