### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by anushkaa-dubey** [mansiruhil13/Bobble-AI#454]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Navbar problem in features page
![Screenshot 2024-10-08 230924](https://github.com/user-attachments/assets/ebc74a80-727a-4f85-ace3-d01382fdc8cc)

### Use Case

Please assign me this issue under gssoc and hacktoberfest 

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by mansiruhil13** [comment]
actually that's assigned already
