### ISSUE TITLE
[Bug]: Fix home page header issue

### ISSUE THREAD

**Issue by devarsheecodess** [mansiruhil13/Bobble-AI#455]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The header is replicated, it is showing up two times

### Add Screenshots

![image](https://github.com/user-attachments/assets/03f305b6-4f55-4980-aa9c-202cd2d5c4f0)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by mansiruhil13** [comment]
but navbar section like home .. improvement already assigned. you can work on double part
