### ISSUE TITLE
[Bug]: Scroll up button fixed at the bottom of the screen

### ISSUE THREAD

**Issue by SagnikGos** [mansiruhil13/Bobble-AI#464]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The scroll up button should be present floating above the page at the bottom right corner of the screen at all times, 
but the scroll button is fixated at the bottom of the page.

#Screenshot of the Bug

![image](https://github.com/user-attachments/assets/5512aae5-9556-457d-94a1-ce891c11a713)

I'm a GSSOC'24 Contributor & a Hacktoberfest Contributor.
Please assign me this issue with appropriate labels with Level1/2/3.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by ritiksingh-01** [comment]
By mistake, I wrote the wrong issue number, sorry for the confusion

**Comment by SagnikGos** [comment]
@ritiksingh-01 all good

**Comment by mansiruhil13** [comment]
there are few changes on home page, make changes in the code according to that.
