### ISSUE TITLE
[Feature Request]: Feature Enhancement: Nearby Hospital Map Integration

### ISSUE THREAD

**Issue by snehhhcodes** [mansiruhil13/Bobble-AI#478]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Implement a "Nearby Hospital" feature that allows users to access a map of nearby hospitals based on their current location. This feature will enhance the emergency response process by enabling users to quickly find and navigate to the nearest healthcare facilities.

### Use Case

1. A user requests an ambulance and, after confirmation, can view nearby hospitals on a map.
2. The user sees the nearest hospitals, their distances, and additional information to make informed decisions while waiting for the ambulance.

### Benefits

1. Enhanced User Experience: Empowers users with immediate access to hospitals during emergencies.
2. Faster Decision Making: Users can choose the closest hospital based on distance and services.
3. Increased Safety: Saves valuable time, potentially saving lives with timely medical attention.
4. Resource Optimization: Improves coordination for ambulance services regarding hospital availability.

### Priority

Medium

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by snehhhcodes** [comment]
@mansiruhil13 Hey review this issue one and if suitable please consider this enhancement for a Level 3 contribution under the GSSoC and Hacktoberfest labels.

**Comment by snehhhcodes** [comment]
@mansiruhil13 any update on this?

**Comment by snehhhcodes** [comment]
@4F24L saw u merging the repo so just wnted to raise concern about my pending raised issue since two days it would be great if you can contact the PA and let me know if the issue is needed or will be assigned or not!!
Thankyou

**Comment by 4F24L** [comment]
You can work on this. And send the final screenshot and if possible a video clip when you are done.
