### ISSUE TITLE
[Bug]: Consistent Navbar

### ISSUE THREAD

**Issue by bm9240** [mansiruhil13/Bobble-AI#513]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The nav bar across the home page is different from the nav across other pages.

### Add Screenshots

![Screenshot 2024-10-09 205328](https://github.com/user-attachments/assets/0adfe533-3bc9-45ff-8ce0-3f9c0dd6e276)
![Screenshot 2024-10-09 205339](https://github.com/user-attachments/assets/891d9811-8bee-4f44-a483-e5d61a98d771)

### What browsers are you seeing the problem on?

Microsoft Edge

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by mansiruhil13** [comment]
use 1st one. not scrollbar

**Comment by bm9240** [comment]
Hello ,
may I please know the reason why it was unassigned ?

**Comment by mansiruhil13** [comment]
done already

**Comment by bm9240** [comment]
ohh Okay !

**Comment by mansiruhil13** [comment]
but some changes occurs, that are assigned recently
