### ISSUE TITLE
[Feature Request]: Footer shoulb aligned at the center 

### ISSUE THREAD

**Issue by Anjalis14** [mansiruhil13/Bobble-AI#520]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

footer must be in the center 

### Use Case

it will attract user 

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Anjalis14** [comment]
@mansiruhil13  plz assign me this

**Comment by mansiruhil13** [comment]
screenshot??

**Comment by Anjalis14** [comment]
![image](https://github.com/user-attachments/assets/78f1f4d9-7f8f-457d-9d06-b2b31337a0c2)
