### ISSUE TITLE
Image Assignment

### ISSUE THREAD

**Issue by Mahesh2k5** [mansiruhil13/Bobble-AI#55]
name: Wrong Image atttached

## Description
In driver.html one of the images is not properly linked

Fixes # (issue)

## Type of Change
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Screenshots (if applicable)
![image](https://github.com/user-attachments/assets/5bf65011-89e7-4f43-b9f0-9ad8d12b3dc7)

## Additional Information
---please allow me to fix it, I'm a beginner and this would be my first open source contribution ,please allow me to contribute to this.

**Comment by mansiruhil13** [comment]
how? i attached and it shows the output: 
![1726252453459](https://github.com/user-attachments/assets/cf7ecb4d-7699-47bb-ab40-2455f2c4f048)

**Comment by Mahesh2k5** [comment]
maybe because you have the image on your local drive but not on github.

**Comment by mansiruhil13** [comment]
> maybe because you have the image on your local drive but not on github. when i added an image to the folder and attached it,it is working properly.

I uploaded image on github, don't know

**Comment by mansiruhil13** [comment]
You can use image either one of these: (for reference)
![images](https://github.com/user-attachments/assets/e9c9c4f1-5adb-4bda-bdae-5314a7d1a2e0)
![Screenshot 2024-10-02 211551](https://github.com/user-attachments/assets/d00719f3-6757-42da-b0b3-8dd1f171c9ef)

**Comment by Mahesh2k5** [comment]
i found it online and attached it already.
if you could please gssoc and relevant labels.
I will PR with the corrected code.
