### ISSUE TITLE
[Bug]:Scroll Bar Appearing on Every Icon in the Features Section

### ISSUE THREAD

**Issue by sahhoArjun097** [mansiruhil13/Bobble-AI#566]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

A scroll bar appears on every icon in the " Features " section, causing layout and visual issues that negatively impact the user experience.

### Add Screenshots

![image](https://github.com/user-attachments/assets/64d204db-c998-4fef-bb7a-12ce6530c0a7)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by mansiruhil13** [comment]
done already
