### ISSUE TITLE
[Bug]: In the Follow Us section show a scrolling bar.

### ISSUE THREAD

**Issue by Patelaman07** [mansiruhil13/Bobble-AI#567]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

 In the Follow Us section show a scrolling section when hover the icons of instagram, facebook etc.

### Add Screenshots

https://github.com/user-attachments/assets/831a7b02-c152-4866-be54-252e0f0801be

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by mansiruhil13** [comment]
done already
