### ISSUE TITLE
[Feature Request]: help in Link/connect all pages

### ISSUE THREAD

**Issue by mansiruhil13** [mansiruhil13/Bobble-AI#57]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

 example signin page then continue to next page

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by 4F24L** [comment]
Can i work on this ? @mansiruhil13

**Comment by mansiruhil13** [comment]
> Can i work on this ? @mansiruhil13

yes

**Comment by 4F24L** [comment]
Should I just link those pages ? Or may I create a landing page to manage all link and roles from one single page ?

**Comment by mansiruhil13** [comment]
> Should I just link those pages ? Or may I create a landing page to manage all link and roles from one single page ?

landing page already assigned, you have to link all pages like in a proper website (like ek button pe click krne pe next page open ho).

**Comment by 4F24L** [comment]
@mansiruhil13 So many PRs are there. Please merge those to get a final look of the website. 

Then, I can connect all the pages in a organized way.

**Comment by mansiruhil13** [comment]
> @mansiruhil13 So many PRs are there. Please merge those to get a final look of the website.
> 
> Then, I can connect all the pages in a organized way.

yes

**Comment by 4F24L** [comment]
why you closed this ??

**Comment by 4F24L** [comment]
What is the actual home page ? 

home.html or index.html

**Comment by mansiruhil13** [comment]
> What is the actual home page ?
> 
> home.html or index.html

both are looking same now??

**Comment by 4F24L** [comment]
Not same.

But index.html is blank,  home.html is organised and designed for the homepage.

**Comment by mansiruhil13** [comment]
> Not same.
> 
> But index.html is blank, home.html is organised and designed for the homepage.

now different, but before both were same

**Comment by 4F24L** [comment]
And... generally index.html is the first page that chrome renders.

Make your index.html as homepage or rename the homepage.html as index.html

**Comment by mansiruhil13** [comment]
> And... generally index.html is the first page that chrome renders.
> 
> Make your index.html as homepage or rename the homepage.html as index.html

done, can you check once?

**Comment by 4F24L** [comment]
Okay

**Comment by coderKrysio** [comment]
Hey @mansiruhil13,
is this issue still open?
