### ISSUE TITLE
Home page enhancement

### ISSUE THREAD

**Issue by Kajalmehta29** [mansiruhil13/Bobble-AI#570]
As shown in the screenshot the sections are not properly aligned which made them look a bit non attractive.
I want to fix this issue.

Please assign this issue to me under gssoc-extd and hacktoberfest.

<img width="1351" alt="Screenshot 2024-10-10 at 8 12 37 PM" src="https://github.com/user-attachments/assets/7e8784af-884a-44d6-ab58-14d423e4a928">

**Comment by mansiruhil13** [comment]
example? can you elaborate?

**Comment by Kajalmehta29** [comment]
As we have 5 sections here and 4 in one line and 1 in another doesn't make it look good. It can be 3-2 either to look a bit systematic.

**Comment by mansiruhil13** [comment]
![Screenshot 2024-10-11 194241](https://github.com/user-attachments/assets/d65e59ec-613e-4ca3-9659-e99dab69aaea)
no, they are in right position. no need to make changes
