### ISSUE TITLE
Improvement of Navbar

### ISSUE THREAD

**Issue by shanvid19** [mansiruhil13/Bobble-AI#574]
Hi @mansiruhil13 !

I would like to work on the Navigation Bar of the Website.

- On the home page, I will improve the design as well as the layout of the nav bar, to make it a little more appealing, and keeping in mind to keep it responsive,
![Screenshot 2024-10-10 200839](https://github.com/user-attachments/assets/c4cea0aa-7154-4c55-b17c-438ce0147ea2)

- Contact Us and Feature webpages lack a navbar. I will add a responsive navbar to them.
![Screenshot 2024-10-10 200914](https://github.com/user-attachments/assets/67f23070-34c2-48fa-b709-2fb0fd6cfee5)
![Screenshot 2024-10-10 200946](https://github.com/user-attachments/assets/e88e58f4-bcaf-4759-865d-e53fe319bbb1)

- Navbar of meet our team page lacks styling. I will add styling to it, which will enhance it.
![Screenshot 2024-10-10 200934](https://github.com/user-attachments/assets/53a76f5d-41cf-48fe-9dc4-63265111f2d0)

Please assign me this issue under the labels 'gssoc-ext' and 'hacktober-accepted'
Thanks!

**Comment by 4F24L** [comment]
These issues are alreaady assigned.
