### ISSUE TITLE
[Bug]: Error on clicking at home while at home page

### ISSUE THREAD

**Issue by OmAmar106** [mansiruhil13/Bobble-AI#578]
### What happened?

In case of clicking at home , when you are already at the home page , it redirects you to a non existent page and shows an error. A video has been attached.

### Add Screenshots

https://github.com/user-attachments/assets/e40783e0-e5ae-4271-8735-a9088384dfa4

**Comment by wgeenath** [comment]
Hi @mansiruhil13 

I also noticed this issue and I would like to fix this.Could you please assign me this issue
