### ISSUE TITLE
[Bug]: Add show password button

### ISSUE THREAD

**Issue by devarsheecodess** [mansiruhil13/Bobble-AI#599]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Login and signup page lack show password button

### Add Screenshots

![image](https://github.com/user-attachments/assets/83435d66-28d3-44c6-aded-07c12b47ed6e)
![image](https://github.com/user-attachments/assets/5f2594f4-6099-4202-bde8-1a949f5df235)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by mansiruhil13** [comment]
show password option already there.
![Screenshot 2024-10-11 193215](https://github.com/user-attachments/assets/44ae4bb0-47d8-4b2d-b846-cd7b2c7e4397)
![Screenshot 2024-10-11 193206](https://github.com/user-attachments/assets/f13eeac7-1963-4836-867d-4101b7b2e823)

**Comment by devarsheecodess** [comment]
Ohh, I thought it is a symbol
