### ISSUE TITLE
[Feature Request]: add the color theme to the app. which will increase the UI apperance. 

### ISSUE THREAD

**Issue by Rohinipilla** [mansiruhil13/Bobble-AI#60]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

To increase the UI apperance and show the app purpose using a color theme.

### Use Case

A color theme makes the app easier to use by quickly showing ambulance availability and status. It helps users make faster decisions and understand the situation at a glance, while also improving the app's look and feel.

### Benefits

It improves user experience

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by mansiruhil13** [comment]
color theme like what? can you give example?

**Comment by Rohinipilla** [comment]
By using gradients in the color theme to show ambulance status and urgency levels. like green means available, and the darker the green, the more ready the ambulance is. Yellow shows the status, with light yellow meaning the ambulance is on the way and darker yellow meaning it’s getting ready. Red shows urgency, where darker red means it’s very urgent. These gradients make it easier for users to quickly see the ambulance availability and urgency.

**Comment by Rohinipilla** [comment]
Thank you

**Comment by dsasa89** [comment]
I CAN FIX THIS IF YOU CAN ASSINGED IT TO ME . THANK YOU

**Comment by Rohinipilla** [comment]
I want to do it. Sorry

**Comment by mansiruhil13** [comment]
> I CAN FIX THIS IF YOU CAN ASSINGED IT TO ME . THANK YOU

assigned already

**Comment by Rohinipilla** [comment]
> okay

can you give level 2 I improve the UI with decent colors and also styles the borders
