### ISSUE TITLE
Add drop-down to mainpage navbar

### ISSUE THREAD

**Issue by devarsheecodess** [mansiruhil13/Bobble-AI#603]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The mainpage / homepage navbar is not responsive and the navbar options are not visible on small screens. Adding a drop-down button can fix this issue

### Add Screenshots

![Screenshot_20241011-195225](https://github.com/user-attachments/assets/a093a3e8-782d-4415-8690-602f35445aff)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by devarsheecodess** [comment]
@mansiruhil13 assign this issue to me

**Comment by mansiruhil13** [comment]
actually landing page already assigned, and navbar some changes also done.
