### ISSUE TITLE
[Bug]: Home Page UI FIX 

### ISSUE THREAD

**Issue by saurabh-dev-vns** [mansiruhil13/Bobble-AI#604]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When I land on the homepage, the responsiveness doesn't work properly on small devices, and on larger devices, some navbar buttons overflow from the navbar.

### Add Screenshots

![Screenshot (8)](https://github.com/user-attachments/assets/1a47dc27-3d69-407b-b7c7-840de2da386a)
![Screenshot (9)](https://github.com/user-attachments/assets/32d106df-c4c6-4cc0-881b-23f5781cf799)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by saurabh-dev-vns** [comment]
@mansiruhil13 , please assign this issue to me.

**Comment by 4F24L** [comment]
Make responsive for smaller screens. @saurabh-dev-vns
