### ISSUE TITLE
[Bug]: Remove double icon box in Team page

### ISSUE THREAD

**Issue by Subhajit-2023-44** [mansiruhil13/Bobble-AI#610]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![Screenshot 2024-10-12 021531](https://github.com/user-attachments/assets/aeee7f77-ce3b-4ab5-8c36-67cc766aee98)

Double "Contact Us" icon box in "Team" page. 

I want to Fixed this issue properly.

@mansiruhil13 please assign me this task.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by AsifQamar** [comment]
@4F24L please assign me this issue
