### ISSUE TITLE
[Bug]: Dark mode not working

### ISSUE THREAD

**Issue by nidhi752** [mansiruhil13/Bobble-AI#615]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I clicked on the dark mode button multiple times, but it is not working

### Add Screenshots

![image](https://github.com/user-attachments/assets/e9d21b00-ccba-46ca-8770-9e17631e9d81)

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by omkumar312** [comment]
I want to work on this issue, please assign me this issue.

**Comment by heizshubham** [comment]
I want to work on this issue, please assign me. @mansiruhil13
