### ISSUE TITLE
Feature Page issue - Navbar missing

### ISSUE THREAD

**Issue by AsifQamar** [mansiruhil13/Bobble-AI#620]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

there is navbar missing from Feature page
priority - HIGH

@mansiruhil13 and @4F24L please assign me this issue with hactober and gssoc tag

### Add Screenshots

<img width="960" alt="Screenshot_155" src="https://github.com/user-attachments/assets/4fc17910-c47c-4882-9d3a-51c63ba94364">

### What browsers are you seeing the problem on?

Firefox

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by SatyamTiwari069** [comment]
Add labels and please assign me the task as for gssoc24 extd

**Comment by mansiruhil13** [comment]
already done.
