### ISSUE TITLE
[Feature Request]: map with contact us page 

### ISSUE THREAD

**Issue by Priyanshi0112** [mansiruhil13/Bobble-AI#628]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The Google Maps integration on the  "Contact Us" page provides users with a seamless way to locate your business. This feature enhances user experience by offering an interactive map that displays your precise location, making it easier for customers to find your address.

### Use Case

1. SEO Benefits: Embedding Google Maps enhances local SEO, improving our visibility in search results for potential customers searching for services in our area.
 
2.Interactive Map Display: Users can zoom in and out, drag the map, and explore the surrounding area.

3.Directions: Visitors can get step-by-step driving, walking, or public transport directions directly from their location to ours.

4.Landmark Visibility: Nearby landmarks and points of interest are highlighted, helping users orient themselves in relation to our business.

5.Mobile-Friendly: The map is responsive, ensuring a smooth experience on both desktop and mobile devices.

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by mansiruhil13** [comment]
any example? screenshot?

**Comment by Priyanshi0112** [comment]
![map with contact](https://github.com/user-attachments/assets/b0221393-5e19-4674-b6f3-35ec6004e052)

**Comment by byteom** [comment]
assign to me

**Comment by coderKrysio** [comment]
Hey @mansiruhil13,
is this issue still available?
I can work on this one quickly
