### ISSUE TITLE
[Bug]: login not work on validation

### ISSUE THREAD

**Issue by isimarjitsingh** [mansiruhil13/Bobble-AI#629]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

as i observe your signup/login page does not work the basis of validation and it also unable to navigate on the home page after login , and i am able to fulfill all this requirements so please assign me this work and i will be verry happy to contribute in it . i will use firebase for authentication ,firebase is a google tool. gssoc extd

### Add Screenshots

this is what i want to say

https://github.com/user-attachments/assets/f1648ae0-6422-433e-a930-5bcfaf5518c5

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by mansiruhil13** [comment]
no need to change in login/sign up page. already many changes occur, now that's enough. login page is final now. 
![Screenshot 2024-10-12 161342](https://github.com/user-attachments/assets/58662016-a42c-4eff-9d22-c55a1af51d7b)
