### ISSUE TITLE
[Feature Request]: Deploy the website

### ISSUE THREAD

**Issue by 4F24L** [mansiruhil13/Bobble-AI#64]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Deploy the website
- So, users can interact.
- Users can create new issues

### Use Case

- We can check the changes in real-time

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by 4F24L** [comment]
@mansiruhil13 
Actually, I can't deploy the website as a contributor. You can as an admin and owner of the repo.

If you want me to deploy, you have to add me as a collaborator or moderator in this repo, which isn't right.
Please deploy soon. Waiting ...

After your deployment, I can start working on issue #57

**Comment by 4F24L** [comment]
Still I can't deploy. 

![image](https://github.com/user-attachments/assets/c344b3a2-119a-458d-aa2e-888ed3172ad5)

Make sure you gave me WRITE ACCESS of this repo.

**Comment by mansiruhil13** [comment]
> Still I can't deploy.
> 
> ![image](https://private-user-images.githubusercontent.com/108697331/373342858-c344b3a2-119a-458d-aa2e-888ed3172ad5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5NzQ2NjEsIm5iZiI6MTcyNzk3NDM2MSwicGF0aCI6Ii8xMDg2OTczMzEvMzczMzQyODU4LWMzNDRiM2EyLTExOWEtNDU4ZC1hYTJlLTg4OGVkMzE3MmFkNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwM1QxNjUyNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MjM4ODRhZmMwMTQ3N2NhOTg5YzhkN2Q2NTU0YjNjYTU4MTVjMzRjZjM4ODFkNWRkNTNkMmMzMzhhNjlmNjRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.vzbW_OI6hOjqLTMWaxlg2OJLg0Vwznc25I21y1LGbxQ)
> 
> Make sure you gave me WRITE ACCESS of this repo.

how to give "write access", actually i am beginner. i have no idea

**Comment by 4F24L** [comment]
Okay, I can understand. I am also learning new things.

I can help you to deploy the website on vercel. So you haven't give write access to me.

**Comment by mansiruhil13** [comment]
> Okay, I can understand. I am also learning new things.
> 
> I can help you to deploy the website on vercel. So you haven't give write access to me.

no, i don't know how

**Comment by 4F24L** [comment]
Check linkedin !

**Comment by 4F24L** [comment]
I am making some basic changes to the code, can you add level 2 and then you will merge. So I will get the points.
Are you agree on it ?!

**Comment by mansiruhil13** [comment]
> I am making some basic changes to the code, can you add level 2 and then you will merge. So I will get the points. Are you agree on it ?!

pull request?

**Comment by 4F24L** [comment]
I will make PR soon ..
