### ISSUE TITLE
[Feature Request]:  Add 3 More Questions to the FAQs Section

### ISSUE THREAD

**Issue by Monojit-Pal** [mansiruhil13/Bobble-AI#661]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to add 3 additional questions to the FAQs section to address more common queries related to the usage of the platform.
![Screenshot 2024-10-13 130246](https://github.com/user-attachments/assets/493d7277-f7f6-4ad8-8538-1011453254c7)
@mansiruhil13 

### Use Case

This feature would enhance the clarity and user experience for new visitors by providing answers to frequently asked questions that aren't currently covered.

### Benefits

By expanding the FAQs, it will improve user engagement, reduce confusion, and minimize repetitive inquiries, ultimately benefiting both users and project maintainers.

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by heizshubham** [comment]
Please assign me this, I want to add more FAQs @mansiruhil13

**Comment by 4F24L** [comment]
Whats those 3 questions? mention !!

**Comment by Monojit-Pal** [comment]
What should I do if the ambulance cannot find my location?
If the ambulance has trouble finding your location, ensure your address is accurate. You can also contact the driver directly through the provided contact information to give specific directions.

Can I request an ambulance for multiple patients?
Yes, you can request an ambulance for multiple patients. Be sure to mention the number of patients and their condition during your request so that appropriate resources can be dispatched.

What happens if I need to cancel my ambulance request?
You can cancel your ambulance request through the system before the ambulance arrives. However, cancellation charges may apply depending on the provider's policy.

@4F24L Please assign me if you think this is good.
