### ISSUE TITLE
[Feature Request]: AI chatbot integration

### ISSUE THREAD

**Issue by Abishakm1507** [mansiruhil13/Bobble-AI#665]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The AI-powered chatbot will serve as an interactive assistant, providing users with immediate responses, guidance, and support while navigating the project. The chatbot will enhance user experience by simplifying interactions, resolving queries, and offering personalized recommendations based on user input.

**Purpose and Functionality:**
The chatbot will serve as an intelligent, automated support system integrated directly into the project’s interface. It will provide users with instant responses to common queries, guidance, and troubleshooting support. The feature will aim to:
- Improve user engagement by offering 24/7 assistance.
- Streamline the process of finding information within the platform.
- Reduce the load on human support by handling repetitive questions and simple requests.

### Use Case

The AI-powered chatbot significantly enhances the functionality and user experience of the live hospital notification mobile application. By providing instant access to information, real-time support, and guidance on using the app’s features, the chatbot helps patients navigate critical situations with ease and confidence, ensuring timely access to necessary medical services.

**1. User Scenario**
As a user of the mobile application that notifies patients of nearby hospitals and ambulance services, you often have questions about the app's features and need immediate assistance in emergencies.

**2. Goals**
Request Assistance: Quickly find information about requesting ambulances or contacting hospitals.
Understand Features: Learn how the app calculates ambulance ETAs and shares location data.
**3. Interaction with the Chatbot**
- Instant Access
       User Query: "How do I request an ambulance?"
      Response: The chatbot,  provides clear instructions on how to request an ambulance and what details are needed.

- Real-Time Support
       User Query: "How is the ETA calculated?"
       Response: The chatbot explains that the ETA is based on real-time traffic data and your location, enhancing 
       understanding of the app's functionality.

- Feature Guidance
        User Query: "How can I update my location?"
        Response: The chatbot guides you on updating your location to ensure timely assistance.

- Emergency Information
        User Query: "What is the nearest hospital?"
        Response: The chatbot retrieves and displays nearby hospitals with contact details based on your GPS location.

### Benefits

**Benefits of the AI Chatbot Feature**

- Improved User Experience

The chatbot provides instant, user-friendly assistance, enabling patients to navigate the app with ease, especially in stressful situations.

- Increased Accessibility

Users can access critical information 24/7 without needing to wait for human support, ensuring they receive timely help during emergencies.

- Enhanced Emergency Response

By facilitating quick access to hospital information and ambulance services, the chatbot can contribute to faster response times, potentially saving lives.

- Real-Time Updates

The chatbot can offer real-time traffic updates and ETA calculations, helping users understand ambulance arrival times and allowing for better planning during emergencies.

### Priority

Medium

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by 4F24L** [comment]
Chatbot is already added.
