### ISSUE TITLE
[Bug]: Website is not responsive

### ISSUE THREAD

**Issue by i-shivii** [mansiruhil13/Bobble-AI#681]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

This website is not responsive for other screen. I will make it responsive. 

### Add Screenshots

![bug](https://github.com/user-attachments/assets/759ee8b9-aed8-4bef-bedb-19a08161af8b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by i-shivii** [comment]
Thank you so much for considering.

**Comment by mansiruhil13** [comment]
that's assigned already
