### ISSUE TITLE
[Bug]:  Navbar's links and invisibility in "Nearby" page.

### ISSUE THREAD

**Issue by i-shivii** [mansiruhil13/Bobble-AI#682]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Navbar is not visible in "Nearby" Page. I will add navbar and enhance its performance by adding links.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by mansiruhil13** [comment]
assigned already
