### ISSUE TITLE
[Bug]: miss-alignment of text in small screen sizes

### ISSUE THREAD

**Issue by srishti023** [mansiruhil13/Bobble-AI#687]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![Screenshot 2024-10-13 234436](https://github.com/user-attachments/assets/fc628a49-efbd-4b91-9a30-62a4d0a04b8c)

the text in home page is not handled correctly for small screen sizes please assign this issue to me.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by mansiruhil13** [comment]
there are few changes done. do changes accordingly

**Comment by srishti023** [comment]
Hey @mansiruhil13,

I have raised an issue, "Map breaks the responsiveness in the contact page" #686 . Can I close this issue and merge it with the one at #686? Also, could you please assign a level2 label on that?

Thanks!
