### ISSUE TITLE
create a "darkmode" mode as well as it's page also

### ISSUE THREAD

**Issue by Arisha2902** [mansiruhil13/Bobble-AI#690]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I will create a "darkmode" botton in navbar,which will change the background to black.

It do will change the backroung to black but I will also assign a theme to whole website for all pages,I will give same hover effect and box shdow effect in dark mode also for all pages.

Things I will do:-

create a "Darkmode " Buttton.
2)Create a dark mode for all pages.
3)make hover and transition effect to all cards and items(items which have hover or any other effect now will have effect in darkmode
also).
screenshot is for blue theme but if you want it can be in red theme as well..

![Screenshot (2)](https://github.com/user-attachments/assets/ef32c010-b2f1-4aeb-b997-a1c26f4e99b8)

![Screenshot (1)](https://github.com/user-attachments/assets/527efb62-ee6c-48ab-8b91-75ab94e887f2)

### Use Case

willl create a darkmode.

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by mansiruhil13** [comment]
done already?
