### ISSUE TITLE
[Bug]: Inconsistent Header Section on Home Page

### ISSUE THREAD

**Issue by we-nita** [mansiruhil13/Bobble-AI#692]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I’ve seen that the header at the top of the home page looks different from the headers on the other pages. This difference can make the website feel less organized and confusing for users.

### Add Screenshots

Header Section of Home Page
![image](https://github.com/user-attachments/assets/235df9ed-3ee1-4c0a-9693-5489c70c4bda)
Feedback, Content, Team, Features,  Page Header
![image](https://github.com/user-attachments/assets/03ef26c4-6ef1-49ab-8687-5fae5f2df287)
Content Page, Team page, header,

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by mansiruhil13** [comment]
already assigned for navbar
