### ISSUE TITLE
[Bug]:  Footer of Home Page is Different from Other Pages

### ISSUE THREAD

**Issue by we-nita** [mansiruhil13/Bobble-AI#694]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I’ve noticed that the footer on the home page looks different from the footers on all the other pages. This inconsistency can affect the overall design and user experience of the website.

### Add Screenshots

Footer in all other pages:
![image](https://github.com/user-attachments/assets/b49994a9-62e6-49da-8def-7201d6a4739f)
Footer on home page
![image](https://github.com/user-attachments/assets/c2f5c4ac-9a15-4bb9-a871-b759edc6f694)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by mansiruhil13** [comment]
assigned already
