### ISSUE TITLE
Add Topics 

### ISSUE THREAD

**Issue by anusha7530** [mansiruhil13/Bobble-AI#7]
In WoB, GitHub Topics will help the discoverability of your project.

I see that you already have great topics on your repository!
I would recommend adding the name of the company like the software you use to build like "vs-code, ghdesktop" to improve your discoverability.

If you are happy with the topics you have, feel free to close this issue.

**Comment by diva711** [comment]
i want to contribute.

**Comment by diva711** [comment]
hello @Durgesh4993 @anusha7530 @mansiruhil13  i'm assigned the "Add Topics" task. but i'm not able to make out what i need to do in it exactly. Could you please brief it for me.
