### ISSUE TITLE
[Feature Request]: Enabling Dark Mode Toggle Button and adding it on every relative page

### ISSUE THREAD

**Issue by Baig-fatema** [mansiruhil13/Bobble-AI#701]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to propose the addition of a dark mode toggle button to enhance the user experience on our website. Dark mode can help reduce eye strain in low-light environments and is increasingly becoming a preferred feature among users.

### Use Case

- **User Scenario**: A user is browsing the website in a dimly lit room. They find it difficult to read the content in the default light mode, causing eye strain. The user can easily toggle to dark mode with a single click, making the content more comfortable to read without disrupting their environment.

### Benefits

- Improved accessibility for users in various lighting conditions.
- A modern feature that aligns with current design trends.

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by AsifQamar** [comment]
@mansiruhil13 assign me this

**Comment by Baig-fatema** [comment]
@mansiruhil13 and @AsifQamar i am already working on it please.
