### ISSUE TITLE
[Bug]: update privacy.html break layout

### ISSUE THREAD

**Issue by Anandha-Vihari** [mansiruhil13/Bobble-AI#708]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![Screenshot 2024-10-14 154601](https://github.com/user-attachments/assets/3a0f9cea-40cf-4301-89f3-e4bd4977e3b2)
update this broken layout

### Add Screenshots

![Screenshot 2024-10-14 154601](https://github.com/user-attachments/assets/7e1fdb2d-6094-41e5-959e-b0c4c2573896)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by rishi998** [comment]
@mansiruhil13 I would like to work on this issue under ggsoc-extd. Kindly assign this issue to me and put necessary labels and levels to this issue.

**Comment by Anandha-Vihari** [comment]
@rishi998 i am ready with my code,please go for other issues
