### ISSUE TITLE
[Feature Request]: ADD A TRANSLATION BUTTON 

### ISSUE THREAD

**Issue by HS202022** [mansiruhil13/Bobble-AI#710]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

ADD A TRANSLATOR IN THE WEBSITE TO MAKE THE USER EXPERIENCE GOOD IT WILL BE HELPFUL FOR THE PEOPLE WHO ARE MORE COMFORTABLE TO THEIR NATIVE LANGUAGES
![Screenshot 2024-10-14 110922](https://github.com/user-attachments/assets/432add7f-84a9-4fec-a9ce-dca3c9c8b5fe)
SAMPLE OF WHAT I WILL ADD

### Use Case

IT CAN BE USED BY THE CONSUMERS WHO ALL CAN ONLY READ WRITE OR SPEAK IN THEIR ON LANGUAGE 

### Priority

Medium

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by savvyjatrana2006** [comment]
@mansiruhil13 plz assign me this issue
