### ISSUE TITLE
[Bug]: dark mode in home page

### ISSUE THREAD

**Issue by ABHI-SHEK-001** [mansiruhil13/Bobble-AI#722]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

dark mode is not looking good in home page i want to improve it

### Add Screenshots

![image](https://github.com/user-attachments/assets/0d19d7d1-a446-476e-9570-da1da22a97d4)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by ABHI-SHEK-001** [comment]
@mansiruhil13  it will not effect his work, but for the safety purpose i will startmy work when he done the changes

**Comment by mansiruhil13** [comment]
> @mansiruhil13 it will not effect his work, but for the safety purpose i will startmy work when he done the changes

but dark theme also has toggle and translator.

**Comment by ABHI-SHEK-001** [comment]
current darkmode is looking good, i don't think so it need further modifications now, so i m closing this issue.
