### ISSUE TITLE
Dark Mode Visibility, Duplicate Navbar, and Layout Issues

### ISSUE THREAD

**Issue by Kavish-Paraswar** [mansiruhil13/Bobble-AI#725]
In dark mode, text within boxes and other areas is not visible, making it difficult to read.
![image](https://github.com/user-attachments/assets/4417db05-13eb-4d9a-82d5-c3f619eb0f68)

![image](https://github.com/user-attachments/assets/aba7741e-1385-4f81-a789-c00e1649d32a)

Additionally, there are duplicate navigation bars, and the layout is misaligned. The "Meet Our Team" section is duplicated
![image](https://github.com/user-attachments/assets/17ef5422-b2a9-4651-8e78-896ac46ba8ad)

Code isn't loading correctly in the browser, which appears to be a code issue. These problems need to be addressed for improved functionality and user experience.
![image](https://github.com/user-attachments/assets/f8644f8a-f5ec-415d-948c-238d97082858)

 I'd like to handle this task under GSOC '24 Extended and request it be assigned at Level 1 or 2. I have strong expertise in HTML, CSS, and JavaScript.

**Comment by mansiruhil13** [comment]
assigned already
