### ISSUE TITLE
[Bug]: unwanted text in the feedback page

### ISSUE THREAD

**Issue by ABHI-SHEK-001** [mansiruhil13/Bobble-AI#726]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

there is an unwanted text at the bottom of the feedback page , i want to correct it

### Add Screenshots

![image](https://github.com/user-attachments/assets/f6916fe8-5ad6-4526-8704-ddc79a783c4f)

### What browsers are you seeing the problem on?

Chrome, Safari

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by mansiruhil13** [comment]
actually blunder has been created. *on all the pages

**Comment by ABHI-SHEK-001** [comment]
@mansiruhil13  ok i will check all the pages
