### ISSUE TITLE
[Bug]: Unwanted text on the top of the Features Page

### ISSUE THREAD

**Issue by CodewMilan** [mansiruhil13/Bobble-AI#728]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### **Issue with unwanted text appearing on top fo the the team tab**
<img width="1274" alt="bad text" src="https://github.com/user-attachments/assets/b72bb879-99cd-46f1-b841-51ac2430b99d">

### **I can also improve the way buttons look, so that the website looks more visually appealing** 

**_Please assign this to me under hacktoberfest and gssoc extd.
Thank You_**

### Add Screenshots

<img width="1274" alt="bad text" src="https://github.com/user-attachments/assets/b72bb879-99cd-46f1-b841-51ac2430b99d">

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by mansiruhil13** [comment]
assigned recenlty
