### ISSUE TITLE
[Bug]: Unwanted navbar components in Team webpage

### ISSUE THREAD

**Issue by DarshanKrishna-DK** [mansiruhil13/Bobble-AI#729]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The duplicate navbar components present on the Team webpage are unnecessary and making the UI/UX bad. 

### Add Screenshots

![Screenshot 2024-10-14 223141](https://github.com/user-attachments/assets/1fbe5021-edc1-4741-b9b2-dfe619edc161)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by mansiruhil13** [comment]
assigned recently
