### ISSUE TITLE
[Feature Request]: Following same design of navbar in all webpages

### ISSUE THREAD

**Issue by DarshanKrishna-DK** [mansiruhil13/Bobble-AI#732]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

As i was going through the website, i found out that the navbar is following 2 different designs. I would like to re-design a common navbar for all webpages. 

**Navbar design in home page**
![Screenshot 2024-10-14 223340](https://github.com/user-attachments/assets/879596f3-44ab-4422-bb56-38bca039ce8b)

**Navbar design in Contact Us page**
![Screenshot 2024-10-14 223405](https://github.com/user-attachments/assets/1fdb4b7e-42c3-42f0-93d7-ae9c1fcc15ce)

### Use Case

Improves the user interface and user experience.
Improves the design of the website.

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by DarshanKrishna-DK** [comment]
I want to work on this issue. Can you assign this issue to me with hacktoberfest and gssoc labels @mansiruhil13 ?

**Comment by mansiruhil13** [comment]
remove translator from navbar. as home navbar is correct. you can improve that. as translator already there below also

**Comment by mansiruhil13** [comment]
on contact us page navbar is wrong

**Comment by DarshanKrishna-DK** [comment]
> remove translator from navbar. as home navbar is correct. you can improve that. as translator already there below also

Sure will remove it.

**Comment by DarshanKrishna-DK** [comment]
By the time i started working on this, the navbar designs had changed but the designs were broken and still were not the same as Home navbar. So i have worked on the current navbar, resolved it. Check out pull request #1121 

The navbar is broken like this in features, team and feedback webpages. The feedback webpage navbar had the "Nearby" webpage missing.
![Screenshot 2024-10-28 211122](https://github.com/user-attachments/assets/60cd40e9-68a7-4639-bfd9-b23efb0228e1)
