### ISSUE TITLE
[Feature Request]: Dark mode option in "Meet our team" page

### ISSUE THREAD

**Issue by VihaShomikha** [mansiruhil13/Bobble-AI#735]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

All other pages except the "Meet Our Team" page has dark/ light mode button. I would like to add the Dark/ Light mode button.

### Use Case

Following of same design pattern.
Improving the UI/UX
Makes the webpage look beautiful

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by VihaShomikha** [comment]
@mansiruhil13 Can you assign this task to me with the hacktoberfest and gssoc tags?

**Comment by mansiruhil13** [comment]
yes navbar assigned already. there has been blunder created
