### ISSUE TITLE
[Bug]: FIX THE OVER WRITE ISSUE 

### ISSUE THREAD

**Issue by HS202022** [mansiruhil13/Bobble-AI#736]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![Screenshot 2024-10-14 223315](https://github.com/user-attachments/assets/4ac6d37a-a193-4cd5-ba0d-78d902dac5fc)
its in multiple pages 

### What browsers are you seeing the problem on?

Firefox, Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by mansiruhil13** [comment]
assigned already
