### ISSUE TITLE
[Bug]: Issue with Home page dark mode 

### ISSUE THREAD

**Issue by VihaShomikha** [mansiruhil13/Bobble-AI#737]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When we select Dark mode for the home page, the component colors are messy and is resulting to bad UI/UX.

### Add Screenshots

![Screenshot 2024-10-14 225352](https://github.com/user-attachments/assets/a9951165-9d8e-4abc-b6e7-5e825296be89)
The Navbar components and there text colors needs to be changed.

The background color of the home page has to be changed and imporved.

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by VihaShomikha** [comment]
@mansiruhil13 Request you to assign me this task with Hacktoberfest and GSSOC tags. Thank you!

**Comment by mansiruhil13** [comment]
assigned already for dark page
