### ISSUE TITLE
[Bug]: Duplicate Elements and multiple navigation bar in team section

### ISSUE THREAD

**Issue by snehhhcodes** [mansiruhil13/Bobble-AI#739]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The team section of website  currently displays two navigation bars, which not only causes visual clutter but also leads to repeated content on the webpage. This redundancy can confuse users and negatively impact the overall user experience.

### Add Screenshots

[screen-capture (3).webm](https://github.com/user-attachments/assets/72ce7ba6-11c8-47de-8351-dad04217d220)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by snehhhcodes** [comment]
@mansiruhil13 assign it to me will fix it too

**Comment by mansiruhil13** [comment]
assigned already.
