### ISSUE TITLE
[Feature Request]: Add animation to the ambtracker.html file

### ISSUE THREAD

**Issue by Dcode-7** [mansiruhil13/Bobble-AI#74]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

We can add a little animation where the marker drops down.
Please check out the video and accept my pull request if you liked the dropping animation.

### Use Case

It would be a nice visual effect after the page loads

### Benefits

https://github.com/user-attachments/assets/caa94a9f-db2f-49be-97e9-92e7b08ac0d0

### Priority

Low

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Dcode-7** [comment]
Please accept my pull request if you liked this animation.

**Comment by mansiruhil13** [comment]
> Please accept my pull request if you liked this animation.

what changes you have made? it seems same

**Comment by mansiruhil13** [comment]
> > Please accept my pull request if you liked this animation.
> 
> what changes you have made? it seems same

in this page, there is issue for live location tracking for ambulance. for ex on google map

**Comment by Dcode-7** [comment]
Earlier the marker was just appearing on the page, now it drops down like a pin. Its a very small change.. please watch the before and after.

https://github.com/user-attachments/assets/f66d649e-8f31-4cb4-abec-db6599ae9468


Uploading Screen Recording 2024-10-03 170353.mp4…

**Comment by Dcode-7** [comment]
After:

Uploading Screen Recording 2024-10-03 170353.mp4…

**Comment by Dcode-7** [comment]
ok i'll read up on google API and see if i can help
