### ISSUE TITLE
[Feature Request]: dark mode of navbar

### ISSUE THREAD

**Issue by rohir1132yadav** [mansiruhil13/Bobble-AI#744]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

in darkmode the text of nav bar(home ,feature,team etc) are not show ,its dissable

### Use Case

in dark mode we apply some different color to so the text

### Benefits

in dark mode we apply some different color to so the text

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by rohir1132yadav** [comment]
i want to work on this issue #744 .please assign me under hactoberfest also

**Comment by mansiruhil13** [comment]
its' assigned already

**Comment by rohir1132yadav** [comment]
but its not show  , please assign me
