### ISSUE TITLE
[Feature Request]: Hover effect on button

### ISSUE THREAD

**Issue by rohir1132yadav** [mansiruhil13/Bobble-AI#746]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

at different places of button  we want to add hover effect 

### Use Case

at different places of button  we want to add hover effect 

### Benefits

it become more attractive

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by rohir1132yadav** [comment]
I want to work on this issue #746 .please assign me this issue under hactoberfest also

**Comment by mansiruhil13** [comment]
page??

**Comment by AsifQamar** [comment]
@mansiruhil13 please assign me this
