### ISSUE TITLE
[Bug]: No User Authentication is done 

### ISSUE THREAD

**Issue by krishkishore972** [mansiruhil13/Bobble-AI#747]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

After fill the sign up form user is not registered on Db.
User authentication is not handled on website

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by mansiruhil13** [comment]
assigned already
