### ISSUE TITLE
[Feature Request]: Feature Enhancement Proposal: Ambulance Booking Form

### ISSUE THREAD

**Issue by snehhhcodes** [mansiruhil13/Bobble-AI#749]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

To enhance the ambulance tracking website, we propose adding an ambulance booking form that streamlines the booking process for users. This form will feature a step-by-step guided process, real-time ambulance availability based on the user's location, a dropdown menu for selecting the type of service (basic, advanced life support, non-emergency transport), and an input field for users to specify their medical condition or urgency level. Additionally, users will have the option to save their details for future bookings.

### Use Case

Users access the ambulance booking section, fill out the form with their location, select the required service type, specify their medical condition, and save their details if desired. Upon submission, they receive a confirmation notification with an estimated arrival time for the ambulance.

### Benefits

 This enhancement will improve user experience by simplifying navigation, ensure faster response times through real-time availability, allow for customization of services, prioritize critical requests, provide convenience for repeat users, and enhance overall efficiency in the booking process.

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by AsifQamar** [comment]
@mansiruhil13 please assign me this

**Comment by snehhhcodes** [comment]
@mansiruhil13 any update on it?
