### ISSUE TITLE
[Bug]: text translastor isn't working

### ISSUE THREAD

**Issue by KrishnaMohanty08** [mansiruhil13/Bobble-AI#764]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

text translator button in the nav bar isn't functional it needs to be removed there are to text translator buttons on the home page due to which log in button in not visible hence need to be addressed
![image](https://github.com/user-attachments/assets/432b4604-1dae-43b0-861f-dc9659035b13)
hence can you assign me the task i would like to work on this

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by 4F24L** [comment]
Fix the nav bar too !!

**Comment by KrishnaMohanty08** [comment]
> Fix the nav bar too !!

sure

**Comment by KrishnaMohanty08** [comment]
> > Fix the nav bar too !!
> 
> sure could you please elaborate?

**Comment by KrishnaMohanty08** [comment]
#816 resolved please check the PR and give feedback if changes needed
