### ISSUE TITLE
[Bug]: Feedback Page footer section is glitched

### ISSUE THREAD

**Issue by Saransh-Jainbu** [mansiruhil13/Bobble-AI#767]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Getting unnecessary message at the footer of feedback page

### Add Screenshots

![Screenshot 2024-10-15 115439](https://github.com/user-attachments/assets/8cce9c95-7c88-4bef-b824-b52fe760caf4)

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by shivankurchavan** [comment]
I’d like to work on this issue

**Comment by Saransh-Jainbu** [comment]
Already created pr please check :)
