### ISSUE TITLE
The icon disappears in Dark mode and there is no hamburger for small screens

### ISSUE THREAD

**Issue by HS202022** [mansiruhil13/Bobble-AI#783]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

https://github.com/user-attachments/assets/6bf1b2f0-7c82-459d-aace-6853d761d3ab

I can add a hamburger icon 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by mansiruhil13** [comment]
changes done already.
