### ISSUE TITLE
[Bug]: Feedback.html and index.html is has lot of unnecessary code in it 

### ISSUE THREAD

**Issue by Anandha-Vihari** [mansiruhil13/Bobble-AI#790]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

feedback.html and index.html code is nearly 800 lines of code,unwanted code
and the code is not in optimized way or good code
i will redesign it from start and remove duplicates and unwanted code lines and purify it
assign this under ggsoc level 3 ....

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by AnandhaVihari** [comment]
@mansiruhil13 can you please assign level3 for this
