### ISSUE TITLE
edit newsletter

### ISSUE THREAD

**Issue by abhi200446** [mansiruhil13/Bobble-AI#793]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

i want to edit the footer section from 
![image](https://github.com/user-attachments/assets/6b78ef73-1f00-435a-9cc9-9756322f8abd)

to
![image](https://github.com/user-attachments/assets/9ee740ad-3811-40c7-9f14-1aa98cee6ece)

### Use Case

would improve the project's functionality, making it more user-friendly and efficient for solving user needs.

### Benefits

The advantage of enhancing features is that it makes the project more appealing, efficient, and better suited to meet user expectations

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by mansiruhil13** [comment]
i think, no need.
