### ISSUE TITLE
[Bug]: Remove Extra Translate button in header

### ISSUE THREAD

**Issue by Subhajit-2023-44** [mansiruhil13/Bobble-AI#798]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

There is a translate button in the header of each page but they are not working and those buttons are not needed as there is a translate button in the bottom left corner of the page to translate.      So I want to remove the translate buttons in header(all page).

@mansiruhil13  please assign me this task.

https://github.com/user-attachments/assets/f9d27e58-b419-408f-bbfd-28fbd76caa6c

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Subhajit-2023-44** [comment]
@mansiruhil13 @4F24L

**Comment by 4F24L** [comment]
Is this something we need to improve!?

**Comment by Subhajit-2023-44** [comment]
> Is this something we need to improve!?

These buttons are not working which doesn't look good and those buttons are not needed as there is a translate button in the bottom left corner of the page to translate. so I just want to remove the translate buttons in header of all page...
