### ISSUE TITLE
### Align Footer Text for Improved UI/UX in Feature, Team, Contact & Feedback Sections.

### ISSUE THREAD

**Issue by NitishKumar525** [mansiruhil13/Bobble-AI#801]
### Is there an existing issue for this?

- [X] I have searched the existing issues

#### Description:
I would like to propose an enhancement to the footer in the **Feature**, **Team**, **Contact**, and **Feedback** sections by aligning the text to the center.

#### Proposed Changes:
- **Text Alignment:** Center-align the text in the footer for all relevant sections to ensure uniformity and a more organized look.
- **Improved Aesthetic:** A centered footer will make the layout feel balanced and professional, especially on different screen sizes, enhancing the visual harmony of the page.
- **Responsive Design:** Ensure the new alignment adapts well to various devices, maintaining readability and a user-friendly interface across all platforms.

#### Benefits
- **Increased Visual Appeal:** By centering the footer text, the layout will feel more cohesive and less cluttered, contributing to a more dynamic and modern UI.
- **Better User Experience:** The centered text will naturally guide the user's eyes, providing a more structured flow to the content.

### Add Screenshots

![Screenshot 2024-10-16 001105](https://github.com/user-attachments/assets/551e3926-e225-4851-bcf0-2c5b8bd6f719)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by mansiruhil13** [comment]
make sure your changes can't make blunder in previous changes or upcoming changes

**Comment by NitishKumar525** [comment]
Don't worry about it @mansiruhil13

**Comment by NitishKumar525** [comment]
Successfully fix all the footer components in center ✅. Now you can
checkout my work accept my pull request ASAP.

Thanks & Regards
