### ISSUE TITLE
[Bug]: issues

### ISSUE THREAD

**Issue by mansiruhil13** [mansiruhil13/Bobble-AI#82]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

in 1st screenshot, header : home ,contact us and about not working
in 2nd: home, features, team, contact not working

### Add Screenshots

![Screenshot 2024-10-03 160812](https://github.com/user-attachments/assets/619caf40-ab79-42f2-a165-72acdef4abd0)
![Screenshot 2024-10-03 160835](https://github.com/user-attachments/assets/7fba116d-24fc-44c0-a0c9-33c68f3e4132)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by 4F24L** [comment]
I can fix this. Can you Assign me ?
