### ISSUE TITLE
[Bug]: Feedback page not working.

### ISSUE THREAD

**Issue by Subhajit-2023-44** [mansiruhil13/Bobble-AI#822]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Feedback page not working(File not found).

I want to Fixed this issue properly.

@mansiruhil13 please assign me this task.

https://github.com/user-attachments/assets/6999c345-5048-45c6-a147-10e88143405d

![Screenshot 2024-10-16 131408](https://github.com/user-attachments/assets/b3400a93-3224-419e-a248-bcd3d4989a49)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Subhajit-2023-44** [comment]
@mansiruhil13 @4F24L

**Comment by mansiruhil13** [comment]
assigned already

**Comment by Subhajit-2023-44** [comment]
> assigned already

My bad
