### ISSUE TITLE
[Bug]: Optimization and removal of unwanted code.

### ISSUE THREAD

**Issue by DarshanKrishna-DK** [mansiruhil13/Bobble-AI#839]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

As i was working on one of the issues, i noticed that there are many lines of code which are unwanted, not used and duplicates. 
Optimization of code and removal of unwanted code will make the website run faster and helps developers for easy understanding. 

### Add Screenshots

![Screenshot 2024-10-16 184236](https://github.com/user-attachments/assets/773f4cbc-f11b-4f97-a1aa-063a064b85a5)
The css styling for a class object has been duplicated in one of the files. There are many duplicates which i noticed as well. 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by DarshanKrishna-DK** [comment]
@mansiruhil13 Request you to assign me this issue with the hacktoberfest and gssoc-extd labels. Thank you!

**Comment by Anandha-Vihari** [comment]
@DarshanKrishna-DK i am working on it presently,it is assigned to me
