### ISSUE TITLE
[Bug]: Improve Header color

### ISSUE THREAD

**Issue by Subhajit-2023-44** [mansiruhil13/Bobble-AI#843]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Features page header background color is different from all pages.. 

I want to Fixed this issue.

@mansiruhil13 please assign me this task.

![Screenshot 2024-10-16 214719](https://github.com/user-attachments/assets/8d06cef0-9f39-4985-b352-d9d9b5716efc)
![Screenshot 2024-10-16 214729](https://github.com/user-attachments/assets/b309a326-7baa-43c6-8a5d-150d90cacfcd)
![Screenshot 2024-10-16 214737](https://github.com/user-attachments/assets/5e52c5be-535c-4343-b704-36b54ba0e056)
![Screenshot 2024-10-16 214748](https://github.com/user-attachments/assets/35847956-37b3-4481-8bb6-6f4d8016f739)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Subhajit-2023-44** [comment]
@mansiruhil13 @4F24L

**Comment by mansiruhil13** [comment]
translate is not there as of now.

**Comment by Subhajit-2023-44** [comment]
> translate is not there now.

Yes
