### ISSUE TITLE
[Bug]: Overlapping of Chatbot button with a button in footer

### ISSUE THREAD

**Issue by DarshanKrishna-DK** [mansiruhil13/Bobble-AI#850]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The chatbot button is overlapping on one more button which takes you to the start of the webpage in the footer. 

Home page footer design is updated and doesnt conflict with the chatbot button but other pages footer design has to be change to address this issue. 

Further more, the design of ContactUs webpage footer is different and has to be updated.

### Add Screenshots

![Screenshot 2024-10-16 233734](https://github.com/user-attachments/assets/a5e68470-9389-4a42-9e65-4f91620824ac)
![Screenshot 2024-10-16 233751](https://github.com/user-attachments/assets/62950ea4-a37b-4894-aa12-178bd83abfd2)
Overlapping of 2 buttons. The chatbot button position can be changed but the UI/UX will be bad, so i am suggesting to update the footer design.

![Screenshot 2024-10-16 233816](https://github.com/user-attachments/assets/5222a744-a5d3-4335-8bd8-78f107228555)
This is the contact us footer

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by DarshanKrishna-DK** [comment]
@mansiruhil13 Can you assign me this task with the labels hacktoberfest and gssoc-extd?

**Comment by mansiruhil13** [comment]
only fix overlapping. not need to change contactus
