### ISSUE TITLE
[Bug]:  Features Tab navbar hover effect issue

### ISSUE THREAD

**Issue by Saransh-Jainbu** [mansiruhil13/Bobble-AI#866]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Title:
Navbar Tab Turns Fully Blue on Hover When on Features Tab

### Description:
There is an issue specifically when the user is on the **Features** tab. When hovering over the navbar, the currently selected tab (Features) turns fully blue, rather than following the expected styling.

### Steps to Reproduce:
1. Navigate to the Features tab.
2. Hover over any part of the navbar.
3. Observe that the selected tab (Features) changes to a fully blue background on hover, instead of the usual hover effect.

### Expected Behavior:
The Features tab should retain its normal appearance (or have a subtle hover effect), consistent with the behavior of the other tabs, without turning fully blue.

### Additional Notes:
- This issue is isolated to the **Features** tab; other tabs don't exhibit this behavior.
- I have investigated the issue and am ready to fix the code.

### Request:
Please assign this issue to me, and I will resolve it promptly.  
Thanks!

### Add Screenshots

![image](https://github.com/user-attachments/assets/67c12333-7547-414b-a25a-1851c11ada5d)

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by mansiruhil13** [comment]
but navbar page already assigned
