### ISSUE TITLE
[Bug]: Fixing inconsistent/missing position of dark mode button across various pages 

### ISSUE THREAD

**Issue by Anousha-Singh** [mansiruhil13/Bobble-AI#871]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Title: Inconsistent Navbar Dark Theme Button Placement

**Description:**
The dark theme button placement in the navbar is inconsistent across different pages of the application:

- On the **Features** page, the button is located on the right side of the login section.
- In the **Our Team** section, the dark theme button is missing entirely.
- In the **Contact** and **Feedback** sections, the button is positioned on the left side.

This inconsistency affects the overall user experience and needs to be addressed.

**Steps to Reproduce:**
1. Navigate to the **Features** page.
2. Check the placement of the dark theme button.
3. Go to the **Our Team** section and note that the button is missing.
4. Visit the **Contact** and **Feedback** sections to see the button's placement on the left side.

**Expected Behavior:**
The dark theme button should have a consistent placement across all pages for better usability.

**Proposed Solution:**
I can fix the issue by ensuring the dark theme button has a consistent placement across all relevant pages.

**Please assign me this issue so I can implement the fix.**

### Add Screenshots

![Screenshot 2024-10-17 134527](https://github.com/user-attachments/assets/629854ec-7c69-42e8-93b3-25c6b0a978ad)
![Screenshot 2024-10-17 134518](https://github.com/user-attachments/assets/a2df7fed-e3bb-41aa-ad9e-e54fc89aacce)
![Screenshot 2024-10-17 134509](https://github.com/user-attachments/assets/6024451a-5895-4452-baa3-a93add05e5f2)
![Screenshot 2024-10-17 134501](https://github.com/user-attachments/assets/114c332b-8ed1-4799-a9c4-e00aa638529e)

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by mansiruhil13** [comment]
already assigned
