### ISSUE TITLE
[Bug]: Extend and integrating Dark Mode to Feedback Page

### ISSUE THREAD

**Issue by DivyaJyothi9** [mansiruhil13/Bobble-AI#874]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Currently, dark mode is implemented on other pages but is not functional on the Feedback page. This issue aims to integrate the existing dark mode feature into the Feedback page to maintain consistency across the site.

**Proposed Solution:**

Ensure that the Feedback page can detect and apply the dark mode settings from the rest of the site.
Update all necessary styles on the Feedback page (background, text, buttons, etc.) to be compatible with dark mode.
Test for visual consistency with the dark mode used on other pages.

### Add Screenshots

![Screenshot (348)](https://github.com/user-attachments/assets/593c1e96-cd0a-44a7-900a-28d4e476dc76)

### What browsers are you seeing the problem on?
Firefox, Chrome, Safari, Microsoft Edge

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by mansiruhil13** [comment]
feedback ui already assigned
