### ISSUE TITLE
[Feature Request]: Feat:adding a new page to display all contributors✨

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [mansiruhil13/Bobble-AI#894]
### Is there an existing issue for this?

- [X] I have searched the existing issues

I want to add a page to showcase all the contributors of this website
@mansiruhil13 can you assign me this issue.

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by mansiruhil13** [comment]
is there a duplicate issue?

**Comment by T-Rahul-prabhu-38** [comment]
it was made by me

**Comment by mansiruhil13** [comment]
> it was made by me 

Why you made another?

**Comment by T-Rahul-prabhu-38** [comment]
Sorry I go thru multiple repos , I usually check but this time I didn't see that I already raised an issue
