### ISSUE TITLE
[Bug]: Improve button text color

### ISSUE THREAD

**Issue by Subhajit-2023-44** [mansiruhil13/Bobble-AI#901]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Button text color(blue) on "Feedback" page is different from all pages. Which doesn't look good...

![Screenshot 2024-10-18 013537](https://github.com/user-attachments/assets/15810a12-7c18-446f-a858-be4e2ae50df5)

In others page button text color(black) -
![Screenshot 2024-10-18 013514](https://github.com/user-attachments/assets/c14eeb0d-7e0f-4e00-bfbe-65a3dfaaf3b2)
![Screenshot 2024-10-18 013521](https://github.com/user-attachments/assets/68df83f1-f7d8-4040-98c3-938f65864f15)
![Screenshot 2024-10-18 013530](https://github.com/user-attachments/assets/e3d2a8de-31d1-44e9-b85e-8d209fb08dff)

I want to Fixed these issue properly.

@mansiruhil13  please assign me this task.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by mansiruhil13** [comment]
navbar already assigned

**Comment by Subhajit-2023-44** [comment]
> navbar already assigned

ok
