### ISSUE TITLE
[Bug]: Navbar 

### ISSUE THREAD

**Issue by Sakshi16175** [mansiruhil13/Bobble-AI#947]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The navbar should be on the top 

### Add Screenshots

![image](https://github.com/user-attachments/assets/c6a15420-ab6e-4686-9af8-c0a0ca728e9c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Sakshi16175** [comment]
i would like to work on this

**Comment by mansiruhil13** [comment]
but there is a landing page. and top to down arrow also there in navbar.

**Comment by mansiruhil13** [comment]
already assigned

**Comment by Sakshi16175** [comment]
no problem
