### ISSUE TITLE
[Bug]: Registration page UI

### ISSUE THREAD

**Issue by KrishChothani** [mansiruhil13/Bobble-AI#949]
### Is there an existing issue for this?

- [x] I have searched the existing issues
       There not any existing issue related ths

### What happened?

Registration page UI alignment is not properly and show some  code

### Add Screenshots

![image](https://github.com/user-attachments/assets/9452b927-dc44-461e-ab11-224cc1537d2f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by mansiruhil13** [comment]
signin or signup assigned already. this page has been broken due to some glitch.
