### ISSUE TITLE
[Bug]: Not open feedback form

### ISSUE THREAD

**Issue by KrishChothani** [mansiruhil13/Bobble-AI#950]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Not opening the feedback form

### Add Screenshots

![image](https://github.com/user-attachments/assets/55f0d29c-4e3a-410d-930d-50bf2c59fb4f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by mansiruhil13** [comment]
its' done already
