### ISSUE TITLE
[Feature Request]: Add a new page to display all contributors 

### ISSUE THREAD

**Issue by Subhajit-2023-44** [mansiruhil13/Bobble-AI#955]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to add a page to showcase all the contributors of this website.

@mansiruhil13  please assign me this task.

### Use Case

![image](https://github.com/user-attachments/assets/7f2d1b0e-5dc4-4ec4-a046-95881633f36a)
..

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Subhajit-2023-44** [comment]
@mansiruhil13

**Comment by mansiruhil13** [comment]
contributors on website?? its' already mentioned on readme file of repo

**Comment by Subhajit-2023-44** [comment]
> contributors on deployment site?? its' already mentioned on readme file of repo. i think, there is no need.

Ok ok
