### ISSUE TITLE
[Bug]: Feedback page error

### ISSUE THREAD

**Issue by Son7c** [mansiruhil13/Bobble-AI#956]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Feedback page shows error 404

### Add Screenshots

![Screenshot 2024-10-19 175600](https://github.com/user-attachments/assets/08a71496-880b-463b-baa1-e24f43d79d8b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by mansiruhil13** [comment]
its' done already
