### ISSUE TITLE
[Feature Request]: Develop new page for get started section

### ISSUE THREAD

**Issue by shivenyadavs** [mansiruhil13/Bobble-AI#958]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I will add a new page which will include register and login section and later go to the booking mechanism.

### Use Case

It will increase a efficiency of booking an ambulance

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by shivenyadavs** [comment]
![Screenshot 2024-10-19 185442](https://github.com/user-attachments/assets/29842072-5beb-4e48-9b8d-3feb9895410e)

**Comment by shivenyadavs** [comment]
@mansiruhil13 please assign this to me

**Comment by mansiruhil13** [comment]
this page has been broken. actually looks like-
![Screenshot 2024-10-06 193430](https://github.com/user-attachments/assets/d47a1ef8-1778-4a36-9e8e-d3b4859f8437)
![Screenshot 2024-10-06 193443](https://github.com/user-attachments/assets/16151457-4c23-4ac8-a238-08efc0cb5ab4)
