### ISSUE TITLE
fevicon

### ISSUE THREAD

**Issue by abhi200446** [mansiruhil13/Bobble-AI#961]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

i will add fevicon for browser page for better user experience  please assign me @mansiruhil13  

### Use Case

it is easier for users to identify and switch between multiple tabs.it easier for users to identify and switch between multiple tabs.

### Benefits

Websites with favicons appear more complete and trustworthy, giving users confidence in the project.

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by mansiruhil13** [comment]
only on home and nearby, its' missing. and it was assigned already. sorry.
