### ISSUE TITLE
Site Map Options Overlapping

### ISSUE THREAD

**Issue by Raj-Ganatra** [mansiruhil13/Bobble-AI#964]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

![side map issue](https://github.com/user-attachments/assets/58ca4488-b0fa-4d2a-aef6-d8143b10ec0f)

"Home","Feature","Team", options are overlapping with "log in get started".

### Use Case

It is not looking good because of overlapping , clicking on links is difficult!

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by anubhavvsharma** [comment]
I can fix this.

**Comment by anubhavvsharma** [comment]
I would like to work on this.

**Comment by Raj-Ganatra** [comment]
@mansiruhil13 please review my Pull Request.
