### ISSUE TITLE
[Bug]: in the home page the buttons are not working properly(home,features,team,contact)

### ISSUE THREAD

**Issue by SwatiSundaray** [mansiruhil13/Bobble-AI#97]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

the buttons are not working properly .they are leading to the same page.

### Add Screenshots

![Screenshot (316)](https://github.com/user-attachments/assets/f60e05eb-c521-48d0-8ccc-353010bc72b5)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [ ] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by shaina123786** [comment]
I would like to solve this issue. Plz assign to me.

**Comment by mansiruhil13** [comment]
already assigned this issue.
