### ISSUE TITLE
[Feature Request]: Addition of Footer Section 

### ISSUE THREAD

**Issue by kritts12** [mansiruhil13/Bobble-AI#98]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

1. The footer will provide users with quick access to key pages like About Us, Contact, and legal policies, along with social media links and contact information. 
2. It will also include features such as newsletter subscription, a site map, and copyright information to enhance navigation and ensure compliance.

### Use Case

The footer enhances user navigation by providing quick access to key pages, social links, contact info, legal policies, and more, improving overall site usability.

### Benefits

A website footer improves navigation, enhances user engagement, ensures legal compliance, and promotes brand visibility through quick access to key pages and social media links.

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [ ] I'm willing to provide further clarification or assistance if needed.

**Comment by jyothimanoj12** [comment]
Can you assign this issue to me

**Comment by mansiruhil13** [comment]
> Can you assign this issue to me

assigned already

**Comment by jyothimanoj12** [comment]
can you please add level

**Comment by jyothimanoj12** [comment]
![Screenshot 2024-10-05 153143](https://github.com/user-attachments/assets/7f1e992b-9355-401b-af27-3520a4b0276b)

i am done with my task , plz say if any further changes are required

**Comment by jyothimanoj12** [comment]
ca

> > Can you assign this issue to me
> 
> assigned already

what about now
